[2022-09-22 11:40:09 DEBUG] [cli:112] ###############################################################################
[2022-09-22 11:40:09 DEBUG] [cli:113] Running command 'run'
[2022-09-22 11:40:09 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-09-22 11:40:09 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-09-22 11:40:09 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-09-22 11:40:09 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-09-22 11:40:09 DEBUG] [caching:24] Building activity cache...
[2022-09-22 11:40:09 DEBUG] [caching:35] Cached 3 activities
[2022-09-22 11:40:09 INFO] [experiment:58] Validating the experiment's syntax
[2022-09-22 11:40:09 DEBUG] [configuration:63] Loading configuration...
[2022-09-22 11:40:09 DEBUG] [secret:78] Loading secrets...
[2022-09-22 11:40:09 DEBUG] [secret:78] Loading secrets...
[2022-09-22 11:40:09 DEBUG] [secret:104] Done loading secrets
[2022-09-22 11:40:09 DEBUG] [secret:104] Done loading secrets
[2022-09-22 11:40:09 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-09-22 11:40:09 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py' does not declare 'validate_control'
[2022-09-22 11:40:09 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py' does not declare 'validate_control'
[2022-09-22 11:40:09 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-09-22 11:40:09 INFO] [experiment:109] Experiment looks valid
[2022-09-22 11:40:09 DEBUG] [caching:42] Clearing activities cache
[2022-09-22 11:40:09 DEBUG] [caching:24] Building activity cache...
[2022-09-22 11:40:09 DEBUG] [caching:35] Cached 3 activities
[2022-09-22 11:40:09 DEBUG] [configuration:63] Loading configuration...
[2022-09-22 11:40:09 DEBUG] [secret:78] Loading secrets...
[2022-09-22 11:40:09 DEBUG] [secret:78] Loading secrets...
[2022-09-22 11:40:09 DEBUG] [secret:104] Done loading secrets
[2022-09-22 11:40:09 DEBUG] [secret:104] Done loading secrets
[2022-09-22 11:40:09 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-09-22 11:40:09 INFO] [run:320] Running experiment: Losing an AZ should not impact availability
[2022-09-22 11:40:09 DEBUG] [run:714] 1 activities will be run in the background
[2022-09-22 11:40:09 DEBUG] [__init__:52] Initializing controls
[2022-09-22 11:40:09 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-09-22 11:40:09 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-09-22 11:40:09 DEBUG] [__init__:61] Initializing control 'slack'
[2022-09-22 11:40:09 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py' does not declare 'configure_control'
[2022-09-22 11:40:09 DEBUG] [__init__:61] Initializing control 'opentracing'
[2022-09-22 11:40:09 DEBUG] [python:196] Control 'configure_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:40:09 DEBUG] [control:41] Configuring opentracing control...
[2022-09-22 11:40:09 DEBUG] [control:47] Creating a opentelemetry tracer
[2022-09-22 11:40:10 DEBUG] [control:61] OpenTracing tracer <opentelemetry.shim.opentracing_shim.TracerShim object at 0x7f83f6b95450> created
[2022-09-22 11:40:10 INFO] [run:344] Steady-state strategy: default
[2022-09-22 11:40:10 INFO] [run:348] Rollbacks strategy: always
[2022-09-22 11:40:10 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-09-22 11:40:10 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-09-22 11:40:10 DEBUG] [__init__:409] Applying before-control 'slack' on 'experiment'
[2022-09-22 11:40:10 DEBUG] [python:196] Control 'before_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:40:10 DEBUG] [__init__:409] Applying before-control 'opentracing' on 'experiment'
[2022-09-22 11:40:10 DEBUG] [python:196] Control 'before_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:40:10 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-09-22 11:40:10 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-09-22 11:40:10 DEBUG] [run:506] Running steady-state hypothesis before the method
[2022-09-22 11:40:10 INFO] [hypothesis:182] Steady state hypothesis: Users should always see the service available
[2022-09-22 11:40:10 DEBUG] [__init__:409] Applying before-control 'reliably' on 'hypothesis'
[2022-09-22 11:40:10 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2022-09-22 11:40:10 DEBUG] [__init__:409] Applying before-control 'slack' on 'hypothesis'
[2022-09-22 11:40:10 DEBUG] [python:196] Control 'before_hypothesis_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:40:10 DEBUG] [__init__:409] Applying before-control 'opentracing' on 'hypothesis'
[2022-09-22 11:40:10 DEBUG] [python:196] Control 'before_hypothesis_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:40:10 DEBUG] [__init__:409] Applying before-control 'reliably' on 'hypothesis'
[2022-09-22 11:40:10 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2022-09-22 11:40:10 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-09-22 11:40:10 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-09-22 11:40:10 DEBUG] [__init__:409] Applying before-control 'slack' on 'activity'
[2022-09-22 11:40:10 DEBUG] [python:196] Control 'before_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:40:10 DEBUG] [__init__:409] Applying before-control 'opentracing' on 'activity'
[2022-09-22 11:40:10 DEBUG] [python:196] Control 'before_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:40:10 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-09-22 11:40:10 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-09-22 11:40:10 INFO] [activity:204] Action: get-lb-unavailable-service-error-count-during-the-last-5m
[2022-09-22 11:40:10 DEBUG] [python:33] Activity 'get-lb-unavailable-service-error-count-during-the-last-5m' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosaws/cloudwatch/probes.py'
[2022-09-22 11:40:10 DEBUG] [__init__:76] Using AWS region 'eu-central-1'
[2022-09-22 11:40:10 DEBUG] [__init__:85] Client will be using profile 'default' from boto3 session
[2022-09-22 11:40:10 DEBUG] [probes:96] Request arguments: {'Namespace': 'AWS/ApplicationELB', 'MetricName': 'HTTPCode_ELB_503_Count', 'StartTime': datetime.datetime(2022, 9, 22, 11, 35, 10, 871982), 'EndTime': datetime.datetime(2022, 9, 22, 11, 40, 10, 871982), 'Period': 300, 'Dimensions': [{'Name': 'LoadBalancer', 'Value': 'app/k8s-default-lbdemo-b42659e47c/bcdbe82dbd3b2dea'}], 'Statistics': ['Sum']}
[2022-09-22 11:40:11 DEBUG] [activity:221]   => succeeded with '0'
[2022-09-22 11:40:11 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-09-22 11:40:11 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-09-22 11:40:11 DEBUG] [__init__:409] Applying after-control 'slack' on 'activity'
[2022-09-22 11:40:11 DEBUG] [python:196] Control 'after_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:40:11 DEBUG] [__init__:409] Applying after-control 'opentracing' on 'activity'
[2022-09-22 11:40:11 DEBUG] [python:196] Control 'after_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:40:11 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-09-22 11:40:11 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-09-22 11:40:11 DEBUG] [hypothesis:221] allowed tolerance is 0
[2022-09-22 11:40:11 INFO] [hypothesis:231] Steady state hypothesis is met!
[2022-09-22 11:40:11 DEBUG] [__init__:409] Applying after-control 'reliably' on 'hypothesis'
[2022-09-22 11:40:11 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2022-09-22 11:40:11 DEBUG] [__init__:409] Applying after-control 'slack' on 'hypothesis'
[2022-09-22 11:40:11 DEBUG] [python:196] Control 'after_hypothesis_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:40:12 DEBUG] [__init__:409] Applying after-control 'opentracing' on 'hypothesis'
[2022-09-22 11:40:12 DEBUG] [python:196] Control 'after_hypothesis_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:40:12 DEBUG] [__init__:409] Applying after-control 'reliably' on 'hypothesis'
[2022-09-22 11:40:12 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2022-09-22 11:40:12 INFO] [run:607] Playing your experiment's method now...
[2022-09-22 11:40:12 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-09-22 11:40:12 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-09-22 11:40:12 DEBUG] [__init__:409] Applying before-control 'slack' on 'method'
[2022-09-22 11:40:12 DEBUG] [python:196] Control 'before_method_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:40:12 DEBUG] [__init__:409] Applying before-control 'opentracing' on 'method'
[2022-09-22 11:40:12 DEBUG] [python:196] Control 'before_method_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:40:12 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-09-22 11:40:12 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-09-22 11:40:12 DEBUG] [activity:132] activity will run in the background
[2022-09-22 11:40:12 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-09-22 11:40:12 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-09-22 11:40:12 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-09-22 11:40:12 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-09-22 11:40:12 DEBUG] [__init__:409] Applying before-control 'slack' on 'activity'
[2022-09-22 11:40:12 DEBUG] [__init__:409] Applying before-control 'slack' on 'activity'
[2022-09-22 11:40:12 DEBUG] [python:196] Control 'before_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:40:12 DEBUG] [python:196] Control 'before_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:40:12 DEBUG] [__init__:409] Applying before-control 'opentracing' on 'activity'
[2022-09-22 11:40:12 DEBUG] [python:196] Control 'before_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:40:12 DEBUG] [__init__:434] Before-control 'opentracing' failed
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaoslib/control/__init__.py", line 415, in apply_controls
        apply_python_control(
      File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaoslib/control/python.py", line 179, in apply_python_control
        func(context=context, **arguments)
      File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py", line 224, in before_activity_control
        scope = tracer.start_active_span(name, child_of=scope.span, finish_on_close=True)
    AttributeError: 'NoneType' object has no attribute 'span'
[2022-09-22 11:40:12 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-09-22 11:40:12 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-09-22 11:40:12 INFO] [activity:198] Action: Inject mild load into our application [in background]
[2022-09-22 11:40:12 DEBUG] [process:52] Running: ../../bin/ddosify -d 330 -n 150 -o stdout-json -t http://k8s-default-lbdemo-b42659e47c-1929532341.eu-central-1.elb.amazonaws.com/consumer/data
[2022-09-22 11:40:12 DEBUG] [__init__:409] Applying before-control 'opentracing' on 'activity'
[2022-09-22 11:40:12 DEBUG] [python:196] Control 'before_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:40:12 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-09-22 11:40:12 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-09-22 11:40:12 INFO] [activity:204] Action: Simulate AZ Failure for ALB
[2022-09-22 11:40:12 DEBUG] [python:33] Activity 'Simulate AZ Failure for ALB' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/azchaosaws/utils.py'
[2022-09-22 11:40:12 DEBUG] [__init__:46] Using AWS region 'eu-central-1'
[2022-09-22 11:40:13 WARNING] [actions:93] [ELBV2] Based on config provided, AZ failure simulation will happen in eu-central-1b for LB(s) ['arn:aws:elasticloadbalancing:eu-central-1:912823331559:loadbalancer/app/k8s-default-lbdemo-b42659e47c/bcdbe82dbd3b2dea']
[2022-09-22 11:40:14 INFO] [actions:113] [ELBV2] Original subnet(s) {'subnet-0be71b8bcc1a209c7', 'subnet-0ecab61e56b44f87e', 'subnet-0bd6f13bfb8796911'}
[2022-09-22 11:40:14 INFO] [actions:116] [ELBV2] Target subnet(s) {'subnet-0bd6f13bfb8796911'}
[2022-09-22 11:40:14 WARNING] [actions:121] [ELBV2] Based on config provided, ALB will change subnets to ['subnet-0be71b8bcc1a209c7', 'subnet-0ecab61e56b44f87e']
[2022-09-22 11:40:14 DEBUG] [actions:242] [ELBV2] Finding for load balancer: ['k8s-default-lbdemo-b42659e47c'].
[2022-09-22 11:40:14 DEBUG] [activity:221]   => succeeded with '{'LoadBalancers': [{'LoadBalancerName': 'k8s-default-lbdemo-b42659e47c', 'Type': 'application', 'Before': {'SubnetIds': ['subnet-0be71b8bcc1a209c7', 'subnet-0ecab61e56b44f87e', 'subnet-0bd6f13bfb8796911']}, 'After': {'SubnetIds': ['subnet-0be71b8bcc1a209c7', 'subnet-0ecab61e56b44f87e']}}], 'AvailabilityZone': 'eu-central-1b', 'DryRun': False}'
[2022-09-22 11:40:14 INFO] [activity:239] Pausing after activity for 300s...
[2022-09-22 11:45:14 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-09-22 11:45:14 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-09-22 11:45:14 DEBUG] [__init__:409] Applying after-control 'slack' on 'activity'
[2022-09-22 11:45:14 DEBUG] [python:196] Control 'after_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:45:15 DEBUG] [__init__:409] Applying after-control 'opentracing' on 'activity'
[2022-09-22 11:45:15 DEBUG] [python:196] Control 'after_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:45:15 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-09-22 11:45:15 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-09-22 11:45:15 DEBUG] [run:840] Waiting for background activities to complete
[2022-09-22 11:45:42 DEBUG] [__init__:157] Data encoding detected as 'ascii' with a confidence of 1.0
[2022-09-22 11:45:42 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': '{"success_perc":100,"fail_perc":0,"success_count":150,"fail_count":0,"avg_duration":0.175,"steps":{"1":{"name":"","status_code_dist":{"200":150},"error_dist":{},"durations":{"connection":0.001,"dns":0,"request_write":0,"response_read":0,"server_processing":0.174,"total":0.175},"success_count":150,"fail_count":0,"success_perc":100,"fail_perc":0}}}\n', 'stderr': ''}'
[2022-09-22 11:45:42 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-09-22 11:45:42 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-09-22 11:45:42 DEBUG] [__init__:409] Applying after-control 'slack' on 'activity'
[2022-09-22 11:45:42 DEBUG] [python:196] Control 'after_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:45:43 DEBUG] [__init__:409] Applying after-control 'opentracing' on 'activity'
[2022-09-22 11:45:43 DEBUG] [python:196] Control 'after_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:45:43 DEBUG] [__init__:434] After-control 'opentracing' failed
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaoslib/control/__init__.py", line 415, in apply_controls
        apply_python_control(
      File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaoslib/control/python.py", line 179, in apply_python_control
        func(context=context, **arguments)
      File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py", line 251, in after_activity_control
        span = scope.span
    AttributeError: 'NoneType' object has no attribute 'span'
[2022-09-22 11:45:43 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-09-22 11:45:43 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-09-22 11:45:43 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-09-22 11:45:43 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-09-22 11:45:43 DEBUG] [__init__:409] Applying after-control 'slack' on 'method'
[2022-09-22 11:45:43 DEBUG] [python:196] Control 'after_method_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:45:43 DEBUG] [__init__:409] Applying after-control 'opentracing' on 'method'
[2022-09-22 11:45:43 DEBUG] [python:196] Control 'after_method_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:45:43 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-09-22 11:45:43 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-09-22 11:45:43 DEBUG] [run:536] Running steady-state hypothesis after the method
[2022-09-22 11:45:43 INFO] [hypothesis:182] Steady state hypothesis: Users should always see the service available
[2022-09-22 11:45:43 DEBUG] [__init__:409] Applying before-control 'reliably' on 'hypothesis'
[2022-09-22 11:45:43 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2022-09-22 11:45:43 DEBUG] [__init__:409] Applying before-control 'slack' on 'hypothesis'
[2022-09-22 11:45:43 DEBUG] [python:196] Control 'before_hypothesis_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:45:43 DEBUG] [__init__:409] Applying before-control 'opentracing' on 'hypothesis'
[2022-09-22 11:45:43 DEBUG] [python:196] Control 'before_hypothesis_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:45:43 DEBUG] [__init__:409] Applying before-control 'reliably' on 'hypothesis'
[2022-09-22 11:45:43 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2022-09-22 11:45:43 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-09-22 11:45:43 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-09-22 11:45:43 DEBUG] [__init__:409] Applying before-control 'slack' on 'activity'
[2022-09-22 11:45:43 DEBUG] [python:196] Control 'before_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:45:43 DEBUG] [__init__:409] Applying before-control 'opentracing' on 'activity'
[2022-09-22 11:45:43 DEBUG] [python:196] Control 'before_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:45:43 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-09-22 11:45:43 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-09-22 11:45:43 INFO] [activity:204] Action: get-lb-unavailable-service-error-count-during-the-last-5m
[2022-09-22 11:45:43 DEBUG] [python:33] Activity 'get-lb-unavailable-service-error-count-during-the-last-5m' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosaws/cloudwatch/probes.py'
[2022-09-22 11:45:43 DEBUG] [__init__:76] Using AWS region 'eu-central-1'
[2022-09-22 11:45:43 DEBUG] [__init__:85] Client will be using profile 'default' from boto3 session
[2022-09-22 11:45:43 DEBUG] [probes:96] Request arguments: {'Namespace': 'AWS/ApplicationELB', 'MetricName': 'HTTPCode_ELB_503_Count', 'StartTime': datetime.datetime(2022, 9, 22, 11, 40, 43, 995938), 'EndTime': datetime.datetime(2022, 9, 22, 11, 45, 43, 995938), 'Period': 300, 'Dimensions': [{'Name': 'LoadBalancer', 'Value': 'app/k8s-default-lbdemo-b42659e47c/bcdbe82dbd3b2dea'}], 'Statistics': ['Sum']}
[2022-09-22 11:45:44 DEBUG] [activity:221]   => succeeded with '0'
[2022-09-22 11:45:44 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-09-22 11:45:44 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-09-22 11:45:44 DEBUG] [__init__:409] Applying after-control 'slack' on 'activity'
[2022-09-22 11:45:44 DEBUG] [python:196] Control 'after_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:45:45 DEBUG] [__init__:409] Applying after-control 'opentracing' on 'activity'
[2022-09-22 11:45:45 DEBUG] [python:196] Control 'after_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:45:45 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-09-22 11:45:45 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-09-22 11:45:45 DEBUG] [hypothesis:221] allowed tolerance is 0
[2022-09-22 11:45:45 INFO] [hypothesis:231] Steady state hypothesis is met!
[2022-09-22 11:45:45 DEBUG] [__init__:409] Applying after-control 'reliably' on 'hypothesis'
[2022-09-22 11:45:45 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2022-09-22 11:45:45 DEBUG] [__init__:409] Applying after-control 'slack' on 'hypothesis'
[2022-09-22 11:45:45 DEBUG] [python:196] Control 'after_hypothesis_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:45:45 DEBUG] [__init__:409] Applying after-control 'opentracing' on 'hypothesis'
[2022-09-22 11:45:45 DEBUG] [python:196] Control 'after_hypothesis_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:45:45 DEBUG] [__init__:409] Applying after-control 'reliably' on 'hypothesis'
[2022-09-22 11:45:45 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2022-09-22 11:45:45 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-09-22 11:45:45 INFO] [run:893] Let's rollback...
[2022-09-22 11:45:45 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-09-22 11:45:45 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-09-22 11:45:45 DEBUG] [__init__:409] Applying before-control 'slack' on 'rollback'
[2022-09-22 11:45:45 DEBUG] [python:196] Control 'before_rollback_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:45:45 DEBUG] [__init__:409] Applying before-control 'opentracing' on 'rollback'
[2022-09-22 11:45:45 DEBUG] [python:196] Control 'before_rollback_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:45:45 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-09-22 11:45:45 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-09-22 11:45:45 INFO] [rollback:30] Rollback: Recover AZ Failure for ALB
[2022-09-22 11:45:45 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-09-22 11:45:45 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-09-22 11:45:45 DEBUG] [__init__:409] Applying before-control 'slack' on 'activity'
[2022-09-22 11:45:45 DEBUG] [python:196] Control 'before_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:45:45 DEBUG] [__init__:409] Applying before-control 'opentracing' on 'activity'
[2022-09-22 11:45:45 DEBUG] [python:196] Control 'before_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:45:45 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-09-22 11:45:45 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-09-22 11:45:45 INFO] [activity:204] Action: Recover AZ Failure for ALB
[2022-09-22 11:45:45 DEBUG] [python:33] Activity 'Recover AZ Failure for ALB' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/azchaosaws/elbv2/actions.py'
[2022-09-22 11:45:45 DEBUG] [__init__:46] Using AWS region 'eu-central-1'
[2022-09-22 11:45:45 WARNING] [actions:186] [ELBV2] Based on the state file found, AZ failure rollback will happen for ELB - k8s-default-lbdemo-b42659e47c
[2022-09-22 11:45:45 INFO] [actions:193] [ELBV2] ELB - k8s-default-lbdemo-b42659e47c - will update its subnets to ['subnet-0be71b8bcc1a209c7', 'subnet-0ecab61e56b44f87e', 'subnet-0bd6f13bfb8796911']
[2022-09-22 11:45:45 DEBUG] [actions:242] [ELBV2] Finding for load balancer: ['k8s-default-lbdemo-b42659e47c'].
[2022-09-22 11:45:47 WARNING] [actions:209] [ELBV2] Completed rollback, removing file (fail_az.elbv2.json) from disk...
[2022-09-22 11:45:47 DEBUG] [activity:221]   => succeeded with 'True'
[2022-09-22 11:45:47 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-09-22 11:45:47 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-09-22 11:45:47 DEBUG] [__init__:409] Applying after-control 'slack' on 'activity'
[2022-09-22 11:45:47 DEBUG] [python:196] Control 'after_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:45:47 DEBUG] [__init__:409] Applying after-control 'opentracing' on 'activity'
[2022-09-22 11:45:47 DEBUG] [python:196] Control 'after_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:45:47 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-09-22 11:45:47 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-09-22 11:45:47 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-09-22 11:45:47 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-09-22 11:45:47 DEBUG] [__init__:409] Applying after-control 'slack' on 'rollback'
[2022-09-22 11:45:47 DEBUG] [python:196] Control 'after_rollback_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:45:47 DEBUG] [__init__:409] Applying after-control 'opentracing' on 'rollback'
[2022-09-22 11:45:47 DEBUG] [python:196] Control 'after_rollback_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:45:47 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-09-22 11:45:47 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-09-22 11:45:47 INFO] [run:458] Experiment ended with status: completed
[2022-09-22 11:45:47 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-09-22 11:45:47 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py'
[2022-09-22 11:45:47 DEBUG] [__init__:29] Reliably client TLS verification: True
[2022-09-22 11:45:47 DEBUG] [__init__:30] Reliably client scheme: https
[2022-09-22 11:45:48 DEBUG] [experiment:47] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/4e6f6a1f-ebac-41c0-be7b-ac79803d896a/executions: 404
[2022-09-22 11:45:48 DEBUG] [__init__:409] Applying after-control 'slack' on 'experiment'
[2022-09-22 11:45:48 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2022-09-22 11:45:48 DEBUG] [__init__:409] Applying after-control 'opentracing' on 'experiment'
[2022-09-22 11:45:48 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:45:48 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-09-22 11:45:48 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py'
[2022-09-22 11:45:48 DEBUG] [__init__:29] Reliably client TLS verification: True
[2022-09-22 11:45:48 DEBUG] [__init__:30] Reliably client scheme: https
[2022-09-22 11:45:49 DEBUG] [experiment:47] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/5653c16d-1e17-44b4-9f12-2fea9b246749/executions: 201
[2022-09-22 11:45:49 DEBUG] [__init__:91] Cleaning up controls
[2022-09-22 11:45:49 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-09-22 11:45:49 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-09-22 11:45:49 DEBUG] [__init__:100] Cleaning up control 'slack'
[2022-09-22 11:45:49 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaosslack/control.py' does not declare 'cleanup_control'
[2022-09-22 11:45:49 DEBUG] [__init__:100] Cleaning up control 'opentracing'
[2022-09-22 11:45:49 DEBUG] [python:196] Control 'cleanup_control' loaded from '/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/chaostracing/control.py'
[2022-09-22 11:45:49 DEBUG] [caching:42] Clearing activities cache
