[2023-04-05T09:47:58.862379+00:00 INFO] [plan:194] ################################################################################
[2023-04-05T09:47:58.862576+00:00 INFO] [plan:195] Starting Reliably experiment: https://app.reliably.dev/api/v1/organization/53c4af8a-6385-4a6a-891d-4286fb3cb8d8/experiments/c71acf34-63ac-46e3-bcc7-d5f2a556a43c/raw
[2023-04-05T09:47:59.266333+00:00 DEBUG] [caching:24] Building activity cache...
[2023-04-05T09:47:59.266653+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-04-05T09:47:59.267443+00:00 INFO] [experiment:58] Validating the experiment's syntax
[2023-04-05T09:47:59.267860+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-04-05T09:47:59.268011+00:00 DEBUG] [secret:78] Loading secrets...
[2023-04-05T09:47:59.268600+00:00 DEBUG] [secret:103] Done loading secrets
[2023-04-05T09:47:59.323553+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2023-04-05T09:47:59.323666+00:00 INFO] [experiment:109] Experiment looks valid
[2023-04-05T09:47:59.324067+00:00 DEBUG] [caching:42] Clearing activities cache
[2023-04-05T09:47:59.324646+00:00 DEBUG] [caching:24] Building activity cache...
[2023-04-05T09:47:59.324961+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-04-05T09:47:59.325320+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-04-05T09:47:59.325665+00:00 DEBUG] [secret:78] Loading secrets...
[2023-04-05T09:47:59.325945+00:00 DEBUG] [secret:103] Done loading secrets
[2023-04-05T09:47:59.326034+00:00 DEBUG] [configuration:160] Loading dynamic configuration...
[2023-04-05T09:47:59.326578+00:00 INFO] [run:369] Running experiment: Latency remains under 200ms
[2023-04-05T09:47:59.329031+00:00 DEBUG] [__init__:64] Initializing controls
[2023-04-05T09:47:59.329128+00:00 DEBUG] [__init__:73] Initializing control 'reliably'
[2023-04-05T09:47:59.329644+00:00 DEBUG] [python:196] Control 'configure_control' loaded from '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py'
[2023-04-05T09:47:59.330254+00:00 DEBUG] [experiment:410] Configure Reliably's experiment control
[2023-04-05T09:47:59.818445+00:00 INFO] [experiment:192] Reliably execution: 3e9a46c0-b9c7-41e3-ae5b-24fbed70e1f5
[2023-04-05T09:48:00.145656+00:00 DEBUG] [experiment:552] Sending plan '8faffc5c-0b4b-4d45-86b0-28e5122a176a' status: running
[2023-04-05T09:48:00.798817+00:00 DEBUG] [experiment:78] Starting Reliably state checker now
[2023-04-05T09:48:00.798965+00:00 INFO] [run:396] Steady-state strategy: after-method-only
[2023-04-05T09:48:00.800632+00:00 INFO] [run:400] Rollbacks strategy: always
[2023-04-05T09:48:00.800977+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'experiment'
[2023-04-05T09:48:00.801232+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2023-04-05T09:48:00.801522+00:00 INFO] [run:663] Playing your experiment's method now...
[2023-04-05T09:48:00.801780+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'method'
[2023-04-05T09:48:00.802041+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2023-04-05T09:48:00.802273+00:00 INFO] [activity:133] No declared activities, let's move on.
[2023-04-05T09:48:00.802495+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'method'
[2023-04-05T09:48:00.802728+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2023-04-05T09:48:00.802966+00:00 DEBUG] [run:590] Running steady-state hypothesis after the method
[2023-04-05T09:48:00.803187+00:00 INFO] [hypothesis:186] Steady state hypothesis: capture-response-time-and-verify-it
[2023-04-05T09:48:00.803423+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'hypothesis'
[2023-04-05T09:48:00.803760+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-04-05T09:48:00.804029+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'activity'
[2023-04-05T09:48:00.804270+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-04-05T09:48:00.804510+00:00 INFO] [activity:215] Probe: measure-endpoint-response-time
[2023-04-05T09:48:01.296513+00:00 DEBUG] [python:33] Activity 'measure-endpoint-response-time' loaded from '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/activities/http/probes.py'
[2023-04-05T09:48:01.868913+00:00 DEBUG] [activity:235]   => succeeded with '0.480662'
[2023-04-05T09:48:02.351032+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'activity'
[2023-04-05T09:48:02.351683+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-04-05T09:48:02.352187+00:00 DEBUG] [hypothesis:226] allowed tolerance is {'name': 'validate-response-time', 'type': 'probe', 'provider': {'func': 'response_time_must_be_under', 'type': 'python', 'module': 'chaosreliably.activities.http.tolerances', 'arguments': {'latency': '${reliably_latency}'}}}
[2023-04-05T09:48:02.352812+00:00 DEBUG] [python:33] Activity 'validate-response-time' loaded from '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/activities/http/tolerances.py'
[2023-04-05T09:48:02.353323+00:00 DEBUG] [tolerances:13] Verify that response time is under: 0.2
[2023-04-05T09:48:02.353871+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'hypothesis'
[2023-04-05T09:48:02.354002+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-04-05T09:48:02.354697+00:00 CRITICAL] [run:601] Steady state probe 'measure-endpoint-response-time' is not in the given tolerance so failing this experiment
[2023-04-05T09:48:02.355097+00:00 WARNING] [run:706] Rollbacks were explicitly requested to be played
[2023-04-05T09:48:02.355196+00:00 INFO] [run:943] Let's rollback...
[2023-04-05T09:48:02.355886+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'rollback'
[2023-04-05T09:48:02.356213+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2023-04-05T09:48:02.356565+00:00 INFO] [rollback:31] No declared rollbacks, let's move on.
[2023-04-05T09:48:02.357090+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'rollback'
[2023-04-05T09:48:02.357530+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2023-04-05T09:48:02.358029+00:00 INFO] [run:510] Experiment ended with status: deviated
[2023-04-05T09:48:02.358339+00:00 INFO] [run:512] The steady-state has deviated, a weakness may have been discovered
[2023-04-05T09:48:02.358763+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'experiment'
[2023-04-05T09:48:02.359125+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_experiment_control'
[2023-04-05T09:48:02.359529+00:00 DEBUG] [__init__:103] Cleaning up controls
[2023-04-05T09:48:02.359840+00:00 DEBUG] [__init__:112] Cleaning up control 'reliably'
[2023-04-05T09:48:02.360156+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2023-04-05T09:48:02.360550+00:00 INFO] [experiment:245] Finishing Reliably execution...
[2023-04-05T09:48:02.790154+00:00 DEBUG] [experiment:160] Stopping Reliably state checker now
[2023-04-05T09:48:03.256673+00:00 DEBUG] [experiment:552] Sending plan '8faffc5c-0b4b-4d45-86b0-28e5122a176a' status: completed
[2023-04-05T09:48:04.047221+00:00 INFO] [experiment:298] Finished Reliably execution. Bye!
[2023-04-05T09:48:04.047498+00:00 DEBUG] [caching:42] Clearing activities cache
