[2022-11-22 16:28:39 DEBUG] [cli:112] ###############################################################################
[2022-11-22 16:28:39 DEBUG] [cli:113] Running command 'run'
[2022-11-22 16:28:39 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-11-22 16:28:39 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-11-22 16:28:39 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 16:28:39 DEBUG] [loader:129] Fetched experiment: 
    {"title":"A simple hello world experiment","method":[{"name":"dis-bonjour","type":"action","provider":{"path":"echo","type":"process","arguments":"${message}"}}],"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"58397051-3da8-488c-9312-eccf388fe7cf","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"n/a","configuration":{"message":"Bonjour !"}}
[2022-11-22 16:28:39 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 16:28:39 DEBUG] [caching:24] Building activity cache...
[2022-11-22 16:28:39 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 16:28:39 INFO] [experiment:58] Validating the experiment's syntax
[2022-11-22 16:28:39 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 16:28:39 DEBUG] [secret:78] Loading secrets...
[2022-11-22 16:28:39 DEBUG] [secret:104] Done loading secrets
[2022-11-22 16:28:39 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-11-22 16:28:39 INFO] [experiment:109] Experiment looks valid
[2022-11-22 16:28:39 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 16:28:39 DEBUG] [caching:24] Building activity cache...
[2022-11-22 16:28:39 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 16:28:39 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 16:28:39 DEBUG] [secret:78] Loading secrets...
[2022-11-22 16:28:39 DEBUG] [secret:104] Done loading secrets
[2022-11-22 16:28:39 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-11-22 16:28:39 INFO] [run:320] Running experiment: A simple hello world experiment
[2022-11-22 16:28:39 DEBUG] [__init__:52] Initializing controls
[2022-11-22 16:28:39 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-11-22 16:28:39 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-11-22 16:28:39 INFO] [run:344] Steady-state strategy: default
[2022-11-22 16:28:39 INFO] [run:348] Rollbacks strategy: always
[2022-11-22 16:28:39 INFO] [run:353] No steady state hypothesis defined. That's ok, just exploring.
[2022-11-22 16:28:39 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-11-22 16:28:39 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-11-22 16:28:39 INFO] [run:607] Playing your experiment's method now...
[2022-11-22 16:28:39 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-11-22 16:28:39 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-11-22 16:28:39 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-11-22 16:28:39 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-11-22 16:28:39 INFO] [activity:204] Action: dis-bonjour
[2022-11-22 16:28:39 DEBUG] [process:52] Running: /usr/bin/echo Bonjour !
[2022-11-22 16:28:39 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'Bonjour !\n', 'stderr': ''}'
[2022-11-22 16:28:39 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-11-22 16:28:39 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-11-22 16:28:39 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-11-22 16:28:39 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-11-22 16:28:39 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-11-22 16:28:39 INFO] [run:893] Let's rollback...
[2022-11-22 16:28:39 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-11-22 16:28:39 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-11-22 16:28:39 INFO] [rollback:27] No declared rollbacks, let's move on.
[2022-11-22 16:28:39 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-11-22 16:28:39 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-11-22 16:28:39 INFO] [run:458] Experiment ended with status: completed
[2022-11-22 16:28:39 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-11-22 16:28:39 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2022-11-22 16:28:39 DEBUG] [__init__:38] Reliably client TLS verification: True
[2022-11-22 16:28:39 DEBUG] [__init__:39] Reliably client scheme: https
[2022-11-22 16:28:40 DEBUG] [experiment:77] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/58397051-3da8-488c-9312-eccf388fe7cf/executions: 201
[2022-11-22 16:28:40 DEBUG] [__init__:91] Cleaning up controls
[2022-11-22 16:28:40 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-11-22 16:28:40 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-11-22 16:28:40 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 16:57:24 DEBUG] [cli:112] ###############################################################################
[2022-11-22 16:57:24 DEBUG] [cli:113] Running command 'run'
[2022-11-22 16:57:24 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-11-22 16:57:25 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-11-22 16:57:25 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 16:57:25 DEBUG] [loader:129] Fetched experiment: 
    {"title":"A simple hello world experiment","method":[{"name":"dis-bonjour","type":"action","provider":{"path":"echo","type":"process","arguments":"${message}"}}],"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"58397051-3da8-488c-9312-eccf388fe7cf","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"n/a","configuration":{"message":"Bonjour !"}}
[2022-11-22 16:57:25 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 16:57:25 DEBUG] [caching:24] Building activity cache...
[2022-11-22 16:57:25 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 16:57:25 INFO] [experiment:58] Validating the experiment's syntax
[2022-11-22 16:57:25 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 16:57:25 DEBUG] [secret:78] Loading secrets...
[2022-11-22 16:57:25 DEBUG] [secret:104] Done loading secrets
[2022-11-22 16:57:25 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-11-22 16:57:25 INFO] [experiment:109] Experiment looks valid
[2022-11-22 16:57:25 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 16:57:25 DEBUG] [caching:24] Building activity cache...
[2022-11-22 16:57:25 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 16:57:25 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 16:57:25 DEBUG] [secret:78] Loading secrets...
[2022-11-22 16:57:25 DEBUG] [secret:104] Done loading secrets
[2022-11-22 16:57:25 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-11-22 16:57:25 INFO] [run:320] Running experiment: A simple hello world experiment
[2022-11-22 16:57:25 DEBUG] [__init__:52] Initializing controls
[2022-11-22 16:57:25 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-11-22 16:57:25 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-11-22 16:57:25 INFO] [run:344] Steady-state strategy: default
[2022-11-22 16:57:25 INFO] [run:348] Rollbacks strategy: always
[2022-11-22 16:57:25 INFO] [run:353] No steady state hypothesis defined. That's ok, just exploring.
[2022-11-22 16:57:25 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-11-22 16:57:25 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-11-22 16:57:25 INFO] [run:607] Playing your experiment's method now...
[2022-11-22 16:57:25 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-11-22 16:57:25 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-11-22 16:57:25 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-11-22 16:57:25 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-11-22 16:57:25 INFO] [activity:204] Action: dis-bonjour
[2022-11-22 16:57:25 DEBUG] [process:52] Running: /usr/bin/echo Bonjour !
[2022-11-22 16:57:25 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'Bonjour !\n', 'stderr': ''}'
[2022-11-22 16:57:25 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-11-22 16:57:25 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-11-22 16:57:25 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-11-22 16:57:25 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-11-22 16:57:25 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-11-22 16:57:25 INFO] [run:893] Let's rollback...
[2022-11-22 16:57:25 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-11-22 16:57:25 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-11-22 16:57:25 INFO] [rollback:27] No declared rollbacks, let's move on.
[2022-11-22 16:57:25 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-11-22 16:57:25 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-11-22 16:57:25 INFO] [run:458] Experiment ended with status: completed
[2022-11-22 16:57:25 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-11-22 16:57:25 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2022-11-22 16:57:25 DEBUG] [__init__:38] Reliably client TLS verification: True
[2022-11-22 16:57:25 DEBUG] [__init__:39] Reliably client scheme: https
[2022-11-22 16:57:26 DEBUG] [experiment:77] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/58397051-3da8-488c-9312-eccf388fe7cf/executions: 201
[2022-11-22 16:57:26 DEBUG] [__init__:91] Cleaning up controls
[2022-11-22 16:57:26 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-11-22 16:57:26 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-11-22 16:57:26 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 17:24:39 DEBUG] [cli:112] ###############################################################################
[2022-11-22 17:24:39 DEBUG] [cli:113] Running command 'run'
[2022-11-22 17:24:39 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-11-22 17:24:40 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-11-22 17:24:40 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 17:24:40 DEBUG] [loader:129] Fetched experiment: 
    {"title":"A simple hello world experiment","method":[{"name":"dis-bonjour","type":"action","provider":{"path":"echo","type":"process","arguments":"${message}"}}],"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"58397051-3da8-488c-9312-eccf388fe7cf","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"n/a","configuration":{"message":"Bonjour !"}}
[2022-11-22 17:24:40 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 17:24:40 DEBUG] [caching:24] Building activity cache...
[2022-11-22 17:24:40 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 17:24:40 INFO] [experiment:58] Validating the experiment's syntax
[2022-11-22 17:24:40 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 17:24:40 DEBUG] [secret:78] Loading secrets...
[2022-11-22 17:24:40 DEBUG] [secret:104] Done loading secrets
[2022-11-22 17:24:40 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-11-22 17:24:40 INFO] [experiment:109] Experiment looks valid
[2022-11-22 17:24:40 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 17:24:40 DEBUG] [caching:24] Building activity cache...
[2022-11-22 17:24:40 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 17:24:40 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 17:24:40 DEBUG] [secret:78] Loading secrets...
[2022-11-22 17:24:40 DEBUG] [secret:104] Done loading secrets
[2022-11-22 17:24:40 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-11-22 17:24:40 INFO] [run:320] Running experiment: A simple hello world experiment
[2022-11-22 17:24:40 DEBUG] [__init__:52] Initializing controls
[2022-11-22 17:24:40 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-11-22 17:24:40 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-11-22 17:24:40 INFO] [run:344] Steady-state strategy: default
[2022-11-22 17:24:40 INFO] [run:348] Rollbacks strategy: always
[2022-11-22 17:24:40 INFO] [run:353] No steady state hypothesis defined. That's ok, just exploring.
[2022-11-22 17:24:40 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-11-22 17:24:40 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-11-22 17:24:40 INFO] [run:607] Playing your experiment's method now...
[2022-11-22 17:24:40 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-11-22 17:24:40 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-11-22 17:24:40 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-11-22 17:24:40 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-11-22 17:24:40 INFO] [activity:204] Action: dis-bonjour
[2022-11-22 17:24:40 DEBUG] [process:52] Running: /usr/bin/echo Bonjour !
[2022-11-22 17:24:40 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'Bonjour !\n', 'stderr': ''}'
[2022-11-22 17:24:40 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-11-22 17:24:40 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-11-22 17:24:40 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-11-22 17:24:40 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-11-22 17:24:40 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-11-22 17:24:40 INFO] [run:893] Let's rollback...
[2022-11-22 17:24:40 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-11-22 17:24:40 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-11-22 17:24:40 INFO] [rollback:27] No declared rollbacks, let's move on.
[2022-11-22 17:24:40 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-11-22 17:24:40 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-11-22 17:24:40 INFO] [run:458] Experiment ended with status: completed
[2022-11-22 17:24:40 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-11-22 17:24:40 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2022-11-22 17:24:40 DEBUG] [__init__:38] Reliably client TLS verification: True
[2022-11-22 17:24:40 DEBUG] [__init__:39] Reliably client scheme: https
[2022-11-22 17:24:40 DEBUG] [experiment:77] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/58397051-3da8-488c-9312-eccf388fe7cf/executions: 201
[2022-11-22 17:24:40 DEBUG] [__init__:91] Cleaning up controls
[2022-11-22 17:24:40 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-11-22 17:24:40 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-11-22 17:24:40 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 17:41:57 DEBUG] [cli:112] ###############################################################################
[2022-11-22 17:41:57 DEBUG] [cli:113] Running command 'run'
[2022-11-22 17:41:57 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-11-22 17:41:58 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-11-22 17:41:58 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 17:41:58 DEBUG] [loader:129] Fetched experiment: 
    {"title":"A simple hello world experiment","method":[{"name":"dis-bonjour","type":"action","provider":{"path":"echo","type":"process","arguments":"${message}"}}],"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"58397051-3da8-488c-9312-eccf388fe7cf","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"n/a","configuration":{"message":"Bonjour !"}}
[2022-11-22 17:41:58 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 17:41:58 DEBUG] [caching:24] Building activity cache...
[2022-11-22 17:41:58 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 17:41:58 INFO] [experiment:58] Validating the experiment's syntax
[2022-11-22 17:41:58 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 17:41:58 DEBUG] [secret:78] Loading secrets...
[2022-11-22 17:41:58 DEBUG] [secret:104] Done loading secrets
[2022-11-22 17:41:58 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-11-22 17:41:58 INFO] [experiment:109] Experiment looks valid
[2022-11-22 17:41:58 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 17:41:58 DEBUG] [caching:24] Building activity cache...
[2022-11-22 17:41:58 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 17:41:58 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 17:41:58 DEBUG] [secret:78] Loading secrets...
[2022-11-22 17:41:58 DEBUG] [secret:104] Done loading secrets
[2022-11-22 17:41:58 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-11-22 17:41:58 INFO] [run:320] Running experiment: A simple hello world experiment
[2022-11-22 17:41:58 DEBUG] [__init__:52] Initializing controls
[2022-11-22 17:41:58 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-11-22 17:41:58 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-11-22 17:41:58 INFO] [run:344] Steady-state strategy: default
[2022-11-22 17:41:58 INFO] [run:348] Rollbacks strategy: always
[2022-11-22 17:41:58 INFO] [run:353] No steady state hypothesis defined. That's ok, just exploring.
[2022-11-22 17:41:58 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-11-22 17:41:58 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-11-22 17:41:58 INFO] [run:607] Playing your experiment's method now...
[2022-11-22 17:41:58 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-11-22 17:41:58 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-11-22 17:41:58 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-11-22 17:41:58 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-11-22 17:41:58 INFO] [activity:204] Action: dis-bonjour
[2022-11-22 17:41:58 DEBUG] [process:52] Running: /usr/bin/echo Bonjour !
[2022-11-22 17:41:58 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'Bonjour !\n', 'stderr': ''}'
[2022-11-22 17:41:58 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-11-22 17:41:58 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-11-22 17:41:58 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-11-22 17:41:58 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-11-22 17:41:58 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-11-22 17:41:58 INFO] [run:893] Let's rollback...
[2022-11-22 17:41:58 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-11-22 17:41:58 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-11-22 17:41:58 INFO] [rollback:27] No declared rollbacks, let's move on.
[2022-11-22 17:41:58 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-11-22 17:41:58 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-11-22 17:41:58 INFO] [run:458] Experiment ended with status: completed
[2022-11-22 17:41:58 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-11-22 17:41:58 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2022-11-22 17:41:58 DEBUG] [__init__:38] Reliably client TLS verification: True
[2022-11-22 17:41:58 DEBUG] [__init__:39] Reliably client scheme: https
[2022-11-22 17:41:59 DEBUG] [experiment:77] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/58397051-3da8-488c-9312-eccf388fe7cf/executions: 201
[2022-11-22 17:41:59 DEBUG] [__init__:91] Cleaning up controls
[2022-11-22 17:41:59 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-11-22 17:41:59 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-11-22 17:41:59 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 17:54:45 DEBUG] [cli:112] ###############################################################################
[2022-11-22 17:54:45 DEBUG] [cli:113] Running command 'run'
[2022-11-22 17:54:45 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-11-22 17:54:46 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-11-22 17:54:46 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 17:54:46 DEBUG] [loader:129] Fetched experiment: 
    {"title":"A simple hello world experiment","method":[{"name":"dis-bonjour","type":"action","provider":{"path":"echo","type":"process","arguments":"${message}"}}],"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"58397051-3da8-488c-9312-eccf388fe7cf","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"n/a","configuration":{"message":"Bonjour !"}}
[2022-11-22 17:54:46 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 17:54:46 DEBUG] [caching:24] Building activity cache...
[2022-11-22 17:54:46 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 17:54:46 INFO] [experiment:58] Validating the experiment's syntax
[2022-11-22 17:54:46 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 17:54:46 DEBUG] [secret:78] Loading secrets...
[2022-11-22 17:54:46 DEBUG] [secret:104] Done loading secrets
[2022-11-22 17:54:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-11-22 17:54:46 INFO] [experiment:109] Experiment looks valid
[2022-11-22 17:54:46 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 17:54:46 DEBUG] [caching:24] Building activity cache...
[2022-11-22 17:54:46 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 17:54:46 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 17:54:46 DEBUG] [secret:78] Loading secrets...
[2022-11-22 17:54:46 DEBUG] [secret:104] Done loading secrets
[2022-11-22 17:54:46 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-11-22 17:54:46 INFO] [run:320] Running experiment: A simple hello world experiment
[2022-11-22 17:54:46 DEBUG] [__init__:52] Initializing controls
[2022-11-22 17:54:46 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-11-22 17:54:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-11-22 17:54:46 INFO] [run:344] Steady-state strategy: default
[2022-11-22 17:54:46 INFO] [run:348] Rollbacks strategy: always
[2022-11-22 17:54:46 INFO] [run:353] No steady state hypothesis defined. That's ok, just exploring.
[2022-11-22 17:54:46 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-11-22 17:54:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-11-22 17:54:46 INFO] [run:607] Playing your experiment's method now...
[2022-11-22 17:54:46 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-11-22 17:54:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-11-22 17:54:46 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-11-22 17:54:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-11-22 17:54:46 INFO] [activity:204] Action: dis-bonjour
[2022-11-22 17:54:46 DEBUG] [process:52] Running: /usr/bin/echo Bonjour !
[2022-11-22 17:54:46 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'Bonjour !\n', 'stderr': ''}'
[2022-11-22 17:54:46 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-11-22 17:54:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-11-22 17:54:46 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-11-22 17:54:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-11-22 17:54:46 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-11-22 17:54:46 INFO] [run:893] Let's rollback...
[2022-11-22 17:54:46 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-11-22 17:54:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-11-22 17:54:46 INFO] [rollback:27] No declared rollbacks, let's move on.
[2022-11-22 17:54:46 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-11-22 17:54:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-11-22 17:54:46 INFO] [run:458] Experiment ended with status: completed
[2022-11-22 17:54:46 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-11-22 17:54:46 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2022-11-22 17:54:46 DEBUG] [__init__:38] Reliably client TLS verification: True
[2022-11-22 17:54:46 DEBUG] [__init__:39] Reliably client scheme: https
[2022-11-22 17:54:46 DEBUG] [experiment:77] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/58397051-3da8-488c-9312-eccf388fe7cf/executions: 201
[2022-11-22 17:54:46 DEBUG] [__init__:91] Cleaning up controls
[2022-11-22 17:54:46 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-11-22 17:54:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-11-22 17:54:46 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 18:27:05 DEBUG] [cli:112] ###############################################################################
[2022-11-22 18:27:05 DEBUG] [cli:113] Running command 'run'
[2022-11-22 18:27:05 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-11-22 18:27:05 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-11-22 18:27:05 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 18:27:21 DEBUG] [loader:129] Fetched experiment: 
    {"title":"A simple hello world experiment","method":[{"name":"dis-bonjour","type":"action","provider":{"path":"echo","type":"process","arguments":"${message}"}}],"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"58397051-3da8-488c-9312-eccf388fe7cf","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"n/a","configuration":{"message":"Bonjour !"}}
[2022-11-22 18:27:21 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 18:27:21 DEBUG] [caching:24] Building activity cache...
[2022-11-22 18:27:21 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 18:27:21 INFO] [experiment:58] Validating the experiment's syntax
[2022-11-22 18:27:21 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 18:27:21 DEBUG] [secret:78] Loading secrets...
[2022-11-22 18:27:21 DEBUG] [secret:104] Done loading secrets
[2022-11-22 18:27:21 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-11-22 18:27:21 INFO] [experiment:109] Experiment looks valid
[2022-11-22 18:27:21 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 18:27:21 DEBUG] [caching:24] Building activity cache...
[2022-11-22 18:27:21 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 18:27:21 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 18:27:21 DEBUG] [secret:78] Loading secrets...
[2022-11-22 18:27:21 DEBUG] [secret:104] Done loading secrets
[2022-11-22 18:27:21 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-11-22 18:27:21 INFO] [run:320] Running experiment: A simple hello world experiment
[2022-11-22 18:27:21 DEBUG] [__init__:52] Initializing controls
[2022-11-22 18:27:21 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-11-22 18:27:21 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-11-22 18:27:21 INFO] [run:344] Steady-state strategy: default
[2022-11-22 18:27:21 INFO] [run:348] Rollbacks strategy: always
[2022-11-22 18:27:21 INFO] [run:353] No steady state hypothesis defined. That's ok, just exploring.
[2022-11-22 18:27:21 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-11-22 18:27:21 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-11-22 18:27:21 INFO] [run:607] Playing your experiment's method now...
[2022-11-22 18:27:21 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-11-22 18:27:21 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-11-22 18:27:21 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-11-22 18:27:21 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-11-22 18:27:21 INFO] [activity:204] Action: dis-bonjour
[2022-11-22 18:27:21 DEBUG] [process:52] Running: /usr/bin/echo Bonjour !
[2022-11-22 18:27:21 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'Bonjour !\n', 'stderr': ''}'
[2022-11-22 18:27:21 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-11-22 18:27:21 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-11-22 18:27:21 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-11-22 18:27:21 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-11-22 18:27:21 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-11-22 18:27:21 INFO] [run:893] Let's rollback...
[2022-11-22 18:27:21 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-11-22 18:27:21 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-11-22 18:27:21 INFO] [rollback:27] No declared rollbacks, let's move on.
[2022-11-22 18:27:21 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-11-22 18:27:21 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-11-22 18:27:21 INFO] [run:458] Experiment ended with status: completed
[2022-11-22 18:27:21 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-11-22 18:27:21 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2022-11-22 18:27:21 DEBUG] [__init__:38] Reliably client TLS verification: True
[2022-11-22 18:27:21 DEBUG] [__init__:39] Reliably client scheme: https
[2022-11-22 18:27:22 DEBUG] [experiment:77] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/58397051-3da8-488c-9312-eccf388fe7cf/executions: 201
[2022-11-22 18:27:22 DEBUG] [__init__:91] Cleaning up controls
[2022-11-22 18:27:22 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-11-22 18:27:22 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-11-22 18:27:22 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 18:48:28 DEBUG] [cli:112] ###############################################################################
[2022-11-22 18:48:28 DEBUG] [cli:113] Running command 'run'
[2022-11-22 18:48:28 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-11-22 18:48:28 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-11-22 18:48:28 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 18:48:29 DEBUG] [loader:129] Fetched experiment: 
    {"title":"A simple hello world experiment","method":[{"name":"dis-bonjour","type":"action","provider":{"path":"echo","type":"process","arguments":"${message}"}}],"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"58397051-3da8-488c-9312-eccf388fe7cf","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"n/a","configuration":{"message":"Bonjour !"}}
[2022-11-22 18:48:29 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 18:48:29 DEBUG] [caching:24] Building activity cache...
[2022-11-22 18:48:29 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 18:48:29 INFO] [experiment:58] Validating the experiment's syntax
[2022-11-22 18:48:29 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 18:48:29 DEBUG] [secret:78] Loading secrets...
[2022-11-22 18:48:29 DEBUG] [secret:104] Done loading secrets
[2022-11-22 18:48:29 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-11-22 18:48:29 INFO] [experiment:109] Experiment looks valid
[2022-11-22 18:48:29 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 18:48:29 DEBUG] [caching:24] Building activity cache...
[2022-11-22 18:48:29 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 18:48:29 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 18:48:29 DEBUG] [secret:78] Loading secrets...
[2022-11-22 18:48:29 DEBUG] [secret:104] Done loading secrets
[2022-11-22 18:48:29 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-11-22 18:48:29 INFO] [run:320] Running experiment: A simple hello world experiment
[2022-11-22 18:48:29 DEBUG] [__init__:52] Initializing controls
[2022-11-22 18:48:29 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-11-22 18:48:29 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-11-22 18:48:29 INFO] [run:344] Steady-state strategy: default
[2022-11-22 18:48:29 INFO] [run:348] Rollbacks strategy: always
[2022-11-22 18:48:29 INFO] [run:353] No steady state hypothesis defined. That's ok, just exploring.
[2022-11-22 18:48:29 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-11-22 18:48:29 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-11-22 18:48:29 INFO] [run:607] Playing your experiment's method now...
[2022-11-22 18:48:29 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-11-22 18:48:29 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-11-22 18:48:29 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-11-22 18:48:29 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-11-22 18:48:29 INFO] [activity:204] Action: dis-bonjour
[2022-11-22 18:48:29 DEBUG] [process:52] Running: /usr/bin/echo Bonjour !
[2022-11-22 18:48:29 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'Bonjour !\n', 'stderr': ''}'
[2022-11-22 18:48:29 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-11-22 18:48:29 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-11-22 18:48:29 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-11-22 18:48:29 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-11-22 18:48:29 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-11-22 18:48:29 INFO] [run:893] Let's rollback...
[2022-11-22 18:48:29 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-11-22 18:48:29 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-11-22 18:48:29 INFO] [rollback:27] No declared rollbacks, let's move on.
[2022-11-22 18:48:29 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-11-22 18:48:29 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-11-22 18:48:29 INFO] [run:458] Experiment ended with status: completed
[2022-11-22 18:48:29 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-11-22 18:48:29 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2022-11-22 18:48:29 DEBUG] [__init__:38] Reliably client TLS verification: True
[2022-11-22 18:48:29 DEBUG] [__init__:39] Reliably client scheme: https
[2022-11-22 18:48:29 DEBUG] [experiment:77] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/58397051-3da8-488c-9312-eccf388fe7cf/executions: 201
[2022-11-22 18:48:29 DEBUG] [__init__:91] Cleaning up controls
[2022-11-22 18:48:29 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-11-22 18:48:29 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-11-22 18:48:29 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 19:01:15 DEBUG] [cli:112] ###############################################################################
[2022-11-22 19:01:15 DEBUG] [cli:113] Running command 'run'
[2022-11-22 19:01:15 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-11-22 19:01:16 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-11-22 19:01:16 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 19:01:16 DEBUG] [loader:129] Fetched experiment: 
    {"title":"A simple hello world experiment","method":[{"name":"dis-bonjour","type":"action","provider":{"path":"echo","type":"process","arguments":"${message}"}}],"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"58397051-3da8-488c-9312-eccf388fe7cf","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"n/a","configuration":{"message":"Bonjour !"}}
[2022-11-22 19:01:16 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 19:01:16 DEBUG] [caching:24] Building activity cache...
[2022-11-22 19:01:16 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 19:01:16 INFO] [experiment:58] Validating the experiment's syntax
[2022-11-22 19:01:16 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 19:01:16 DEBUG] [secret:78] Loading secrets...
[2022-11-22 19:01:16 DEBUG] [secret:104] Done loading secrets
[2022-11-22 19:01:16 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-11-22 19:01:16 INFO] [experiment:109] Experiment looks valid
[2022-11-22 19:01:16 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 19:01:16 DEBUG] [caching:24] Building activity cache...
[2022-11-22 19:01:16 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 19:01:16 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 19:01:16 DEBUG] [secret:78] Loading secrets...
[2022-11-22 19:01:16 DEBUG] [secret:104] Done loading secrets
[2022-11-22 19:01:16 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-11-22 19:01:16 INFO] [run:320] Running experiment: A simple hello world experiment
[2022-11-22 19:01:16 DEBUG] [__init__:52] Initializing controls
[2022-11-22 19:01:16 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-11-22 19:01:16 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-11-22 19:01:16 INFO] [run:344] Steady-state strategy: default
[2022-11-22 19:01:16 INFO] [run:348] Rollbacks strategy: always
[2022-11-22 19:01:16 INFO] [run:353] No steady state hypothesis defined. That's ok, just exploring.
[2022-11-22 19:01:16 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-11-22 19:01:16 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-11-22 19:01:16 INFO] [run:607] Playing your experiment's method now...
[2022-11-22 19:01:16 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-11-22 19:01:16 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-11-22 19:01:16 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-11-22 19:01:16 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-11-22 19:01:16 INFO] [activity:204] Action: dis-bonjour
[2022-11-22 19:01:16 DEBUG] [process:52] Running: /usr/bin/echo Bonjour !
[2022-11-22 19:01:16 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'Bonjour !\n', 'stderr': ''}'
[2022-11-22 19:01:16 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-11-22 19:01:16 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-11-22 19:01:16 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-11-22 19:01:16 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-11-22 19:01:16 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-11-22 19:01:16 INFO] [run:893] Let's rollback...
[2022-11-22 19:01:16 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-11-22 19:01:16 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-11-22 19:01:16 INFO] [rollback:27] No declared rollbacks, let's move on.
[2022-11-22 19:01:16 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-11-22 19:01:16 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-11-22 19:01:16 INFO] [run:458] Experiment ended with status: completed
[2022-11-22 19:01:16 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-11-22 19:01:16 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2022-11-22 19:01:16 DEBUG] [__init__:38] Reliably client TLS verification: True
[2022-11-22 19:01:16 DEBUG] [__init__:39] Reliably client scheme: https
[2022-11-22 19:01:17 DEBUG] [experiment:77] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/58397051-3da8-488c-9312-eccf388fe7cf/executions: 201
[2022-11-22 19:01:17 DEBUG] [__init__:91] Cleaning up controls
[2022-11-22 19:01:17 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-11-22 19:01:17 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-11-22 19:01:17 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 19:22:17 DEBUG] [cli:112] ###############################################################################
[2022-11-22 19:22:17 DEBUG] [cli:113] Running command 'run'
[2022-11-22 19:22:17 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-11-22 19:22:17 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-11-22 19:22:17 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 19:22:17 DEBUG] [loader:129] Fetched experiment: 
    {"title":"A simple hello world experiment","method":[{"name":"dis-bonjour","type":"action","provider":{"path":"echo","type":"process","arguments":"${message}"}}],"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"58397051-3da8-488c-9312-eccf388fe7cf","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"n/a","configuration":{"message":"Bonjour !"}}
[2022-11-22 19:22:17 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 19:22:17 DEBUG] [caching:24] Building activity cache...
[2022-11-22 19:22:17 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 19:22:17 INFO] [experiment:58] Validating the experiment's syntax
[2022-11-22 19:22:17 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 19:22:17 DEBUG] [secret:78] Loading secrets...
[2022-11-22 19:22:17 DEBUG] [secret:104] Done loading secrets
[2022-11-22 19:22:18 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-11-22 19:22:18 INFO] [experiment:109] Experiment looks valid
[2022-11-22 19:22:18 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 19:22:18 DEBUG] [caching:24] Building activity cache...
[2022-11-22 19:22:18 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 19:22:18 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 19:22:18 DEBUG] [secret:78] Loading secrets...
[2022-11-22 19:22:18 DEBUG] [secret:104] Done loading secrets
[2022-11-22 19:22:18 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-11-22 19:22:18 INFO] [run:320] Running experiment: A simple hello world experiment
[2022-11-22 19:22:18 DEBUG] [__init__:52] Initializing controls
[2022-11-22 19:22:18 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-11-22 19:22:18 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-11-22 19:22:18 INFO] [run:344] Steady-state strategy: default
[2022-11-22 19:22:18 INFO] [run:348] Rollbacks strategy: always
[2022-11-22 19:22:18 INFO] [run:353] No steady state hypothesis defined. That's ok, just exploring.
[2022-11-22 19:22:18 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-11-22 19:22:18 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-11-22 19:22:18 INFO] [run:607] Playing your experiment's method now...
[2022-11-22 19:22:18 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-11-22 19:22:18 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-11-22 19:22:18 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-11-22 19:22:18 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-11-22 19:22:18 INFO] [activity:204] Action: dis-bonjour
[2022-11-22 19:22:18 DEBUG] [process:52] Running: /usr/bin/echo Bonjour !
[2022-11-22 19:22:18 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'Bonjour !\n', 'stderr': ''}'
[2022-11-22 19:22:18 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-11-22 19:22:18 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-11-22 19:22:18 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-11-22 19:22:18 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-11-22 19:22:18 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-11-22 19:22:18 INFO] [run:893] Let's rollback...
[2022-11-22 19:22:18 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-11-22 19:22:18 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-11-22 19:22:18 INFO] [rollback:27] No declared rollbacks, let's move on.
[2022-11-22 19:22:18 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-11-22 19:22:18 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-11-22 19:22:18 INFO] [run:458] Experiment ended with status: completed
[2022-11-22 19:22:18 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-11-22 19:22:18 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2022-11-22 19:22:18 DEBUG] [__init__:38] Reliably client TLS verification: True
[2022-11-22 19:22:18 DEBUG] [__init__:39] Reliably client scheme: https
[2022-11-22 19:22:18 DEBUG] [experiment:77] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/58397051-3da8-488c-9312-eccf388fe7cf/executions: 201
[2022-11-22 19:22:18 DEBUG] [__init__:91] Cleaning up controls
[2022-11-22 19:22:18 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-11-22 19:22:18 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-11-22 19:22:18 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 19:36:17 DEBUG] [cli:112] ###############################################################################
[2022-11-22 19:36:17 DEBUG] [cli:113] Running command 'run'
[2022-11-22 19:36:17 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-11-22 19:36:18 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-11-22 19:36:18 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 19:36:19 DEBUG] [loader:129] Fetched experiment: 
    {"title":"A simple hello world experiment","method":[{"name":"dis-bonjour","type":"action","provider":{"path":"echo","type":"process","arguments":"${message}"}}],"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"58397051-3da8-488c-9312-eccf388fe7cf","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"n/a","configuration":{"message":"Bonjour !"}}
[2022-11-22 19:36:19 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 19:36:19 DEBUG] [caching:24] Building activity cache...
[2022-11-22 19:36:19 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 19:36:19 INFO] [experiment:58] Validating the experiment's syntax
[2022-11-22 19:36:19 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 19:36:19 DEBUG] [secret:78] Loading secrets...
[2022-11-22 19:36:19 DEBUG] [secret:104] Done loading secrets
[2022-11-22 19:36:19 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-11-22 19:36:19 INFO] [experiment:109] Experiment looks valid
[2022-11-22 19:36:19 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 19:36:19 DEBUG] [caching:24] Building activity cache...
[2022-11-22 19:36:19 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 19:36:19 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 19:36:19 DEBUG] [secret:78] Loading secrets...
[2022-11-22 19:36:19 DEBUG] [secret:104] Done loading secrets
[2022-11-22 19:36:19 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-11-22 19:36:19 INFO] [run:320] Running experiment: A simple hello world experiment
[2022-11-22 19:36:19 DEBUG] [__init__:52] Initializing controls
[2022-11-22 19:36:19 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-11-22 19:36:19 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-11-22 19:36:19 INFO] [run:344] Steady-state strategy: default
[2022-11-22 19:36:19 INFO] [run:348] Rollbacks strategy: always
[2022-11-22 19:36:19 INFO] [run:353] No steady state hypothesis defined. That's ok, just exploring.
[2022-11-22 19:36:19 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-11-22 19:36:19 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-11-22 19:36:19 INFO] [run:607] Playing your experiment's method now...
[2022-11-22 19:36:19 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-11-22 19:36:19 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-11-22 19:36:19 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-11-22 19:36:19 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-11-22 19:36:19 INFO] [activity:204] Action: dis-bonjour
[2022-11-22 19:36:19 DEBUG] [process:52] Running: /usr/bin/echo Bonjour !
[2022-11-22 19:36:19 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'Bonjour !\n', 'stderr': ''}'
[2022-11-22 19:36:19 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-11-22 19:36:19 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-11-22 19:36:19 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-11-22 19:36:19 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-11-22 19:36:19 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-11-22 19:36:19 INFO] [run:893] Let's rollback...
[2022-11-22 19:36:19 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-11-22 19:36:19 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-11-22 19:36:19 INFO] [rollback:27] No declared rollbacks, let's move on.
[2022-11-22 19:36:19 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-11-22 19:36:19 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-11-22 19:36:19 INFO] [run:458] Experiment ended with status: completed
[2022-11-22 19:36:19 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-11-22 19:36:19 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2022-11-22 19:36:19 DEBUG] [__init__:38] Reliably client TLS verification: True
[2022-11-22 19:36:19 DEBUG] [__init__:39] Reliably client scheme: https
[2022-11-22 19:36:19 DEBUG] [experiment:77] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/58397051-3da8-488c-9312-eccf388fe7cf/executions: 201
[2022-11-22 19:36:19 DEBUG] [__init__:91] Cleaning up controls
[2022-11-22 19:36:19 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-11-22 19:36:19 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-11-22 19:36:19 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 19:49:12 DEBUG] [cli:112] ###############################################################################
[2022-11-22 19:49:12 DEBUG] [cli:113] Running command 'run'
[2022-11-22 19:49:12 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-11-22 19:49:13 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-11-22 19:49:13 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 19:49:13 DEBUG] [loader:129] Fetched experiment: 
    {"title":"A simple hello world experiment","method":[{"name":"dis-bonjour","type":"action","provider":{"path":"echo","type":"process","arguments":"${message}"}}],"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"58397051-3da8-488c-9312-eccf388fe7cf","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"n/a","configuration":{"message":"Bonjour !"}}
[2022-11-22 19:49:13 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 19:49:13 DEBUG] [caching:24] Building activity cache...
[2022-11-22 19:49:13 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 19:49:13 INFO] [experiment:58] Validating the experiment's syntax
[2022-11-22 19:49:13 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 19:49:13 DEBUG] [secret:78] Loading secrets...
[2022-11-22 19:49:13 DEBUG] [secret:104] Done loading secrets
[2022-11-22 19:49:13 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-11-22 19:49:13 INFO] [experiment:109] Experiment looks valid
[2022-11-22 19:49:13 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 19:49:13 DEBUG] [caching:24] Building activity cache...
[2022-11-22 19:49:13 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 19:49:13 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 19:49:13 DEBUG] [secret:78] Loading secrets...
[2022-11-22 19:49:13 DEBUG] [secret:104] Done loading secrets
[2022-11-22 19:49:13 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-11-22 19:49:13 INFO] [run:320] Running experiment: A simple hello world experiment
[2022-11-22 19:49:13 DEBUG] [__init__:52] Initializing controls
[2022-11-22 19:49:13 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-11-22 19:49:13 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-11-22 19:49:13 INFO] [run:344] Steady-state strategy: default
[2022-11-22 19:49:13 INFO] [run:348] Rollbacks strategy: always
[2022-11-22 19:49:13 INFO] [run:353] No steady state hypothesis defined. That's ok, just exploring.
[2022-11-22 19:49:13 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-11-22 19:49:13 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-11-22 19:49:13 INFO] [run:607] Playing your experiment's method now...
[2022-11-22 19:49:13 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-11-22 19:49:13 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-11-22 19:49:13 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-11-22 19:49:13 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-11-22 19:49:13 INFO] [activity:204] Action: dis-bonjour
[2022-11-22 19:49:13 DEBUG] [process:52] Running: /usr/bin/echo Bonjour !
[2022-11-22 19:49:13 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'Bonjour !\n', 'stderr': ''}'
[2022-11-22 19:49:13 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-11-22 19:49:13 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-11-22 19:49:13 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-11-22 19:49:13 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-11-22 19:49:13 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-11-22 19:49:13 INFO] [run:893] Let's rollback...
[2022-11-22 19:49:13 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-11-22 19:49:13 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-11-22 19:49:13 INFO] [rollback:27] No declared rollbacks, let's move on.
[2022-11-22 19:49:13 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-11-22 19:49:13 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-11-22 19:49:13 INFO] [run:458] Experiment ended with status: completed
[2022-11-22 19:49:13 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-11-22 19:49:13 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2022-11-22 19:49:13 DEBUG] [__init__:38] Reliably client TLS verification: True
[2022-11-22 19:49:13 DEBUG] [__init__:39] Reliably client scheme: https
[2022-11-22 19:49:13 DEBUG] [experiment:77] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/58397051-3da8-488c-9312-eccf388fe7cf/executions: 201
[2022-11-22 19:49:13 DEBUG] [__init__:91] Cleaning up controls
[2022-11-22 19:49:13 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-11-22 19:49:13 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-11-22 19:49:13 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 20:07:50 DEBUG] [cli:112] ###############################################################################
[2022-11-22 20:07:50 DEBUG] [cli:113] Running command 'run'
[2022-11-22 20:07:50 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-11-22 20:07:50 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-11-22 20:07:50 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 20:07:50 DEBUG] [loader:129] Fetched experiment: 
    {"title":"A simple hello world experiment","method":[{"name":"dis-bonjour","type":"action","provider":{"path":"echo","type":"process","arguments":"${message}"}}],"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"58397051-3da8-488c-9312-eccf388fe7cf","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"n/a","configuration":{"message":"Bonjour !"}}
[2022-11-22 20:07:50 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 20:07:50 DEBUG] [caching:24] Building activity cache...
[2022-11-22 20:07:50 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 20:07:50 INFO] [experiment:58] Validating the experiment's syntax
[2022-11-22 20:07:50 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 20:07:50 DEBUG] [secret:78] Loading secrets...
[2022-11-22 20:07:50 DEBUG] [secret:104] Done loading secrets
[2022-11-22 20:07:50 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-11-22 20:07:50 INFO] [experiment:109] Experiment looks valid
[2022-11-22 20:07:50 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 20:07:50 DEBUG] [caching:24] Building activity cache...
[2022-11-22 20:07:50 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 20:07:50 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 20:07:50 DEBUG] [secret:78] Loading secrets...
[2022-11-22 20:07:50 DEBUG] [secret:104] Done loading secrets
[2022-11-22 20:07:50 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-11-22 20:07:50 INFO] [run:320] Running experiment: A simple hello world experiment
[2022-11-22 20:07:50 DEBUG] [__init__:52] Initializing controls
[2022-11-22 20:07:50 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-11-22 20:07:50 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-11-22 20:07:50 INFO] [run:344] Steady-state strategy: default
[2022-11-22 20:07:50 INFO] [run:348] Rollbacks strategy: always
[2022-11-22 20:07:50 INFO] [run:353] No steady state hypothesis defined. That's ok, just exploring.
[2022-11-22 20:07:50 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-11-22 20:07:50 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-11-22 20:07:50 INFO] [run:607] Playing your experiment's method now...
[2022-11-22 20:07:50 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-11-22 20:07:50 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-11-22 20:07:50 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-11-22 20:07:50 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-11-22 20:07:50 INFO] [activity:204] Action: dis-bonjour
[2022-11-22 20:07:50 DEBUG] [process:52] Running: /usr/bin/echo Bonjour !
[2022-11-22 20:07:50 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'Bonjour !\n', 'stderr': ''}'
[2022-11-22 20:07:50 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-11-22 20:07:50 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-11-22 20:07:50 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-11-22 20:07:50 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-11-22 20:07:50 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-11-22 20:07:50 INFO] [run:893] Let's rollback...
[2022-11-22 20:07:50 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-11-22 20:07:50 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-11-22 20:07:50 INFO] [rollback:27] No declared rollbacks, let's move on.
[2022-11-22 20:07:50 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-11-22 20:07:50 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-11-22 20:07:50 INFO] [run:458] Experiment ended with status: completed
[2022-11-22 20:07:50 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-11-22 20:07:50 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2022-11-22 20:07:50 DEBUG] [__init__:38] Reliably client TLS verification: True
[2022-11-22 20:07:50 DEBUG] [__init__:39] Reliably client scheme: https
[2022-11-22 20:07:51 DEBUG] [experiment:77] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/58397051-3da8-488c-9312-eccf388fe7cf/executions: 201
[2022-11-22 20:07:51 DEBUG] [__init__:91] Cleaning up controls
[2022-11-22 20:07:51 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-11-22 20:07:51 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-11-22 20:07:51 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 20:29:25 DEBUG] [cli:112] ###############################################################################
[2022-11-22 20:29:25 DEBUG] [cli:113] Running command 'run'
[2022-11-22 20:29:25 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-11-22 20:29:25 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-11-22 20:29:25 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 20:29:25 DEBUG] [loader:129] Fetched experiment: 
    {"title":"A simple hello world experiment","method":[{"name":"dis-bonjour","type":"action","provider":{"path":"echo","type":"process","arguments":"${message}"}}],"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"58397051-3da8-488c-9312-eccf388fe7cf","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"n/a","configuration":{"message":"Bonjour !"}}
[2022-11-22 20:29:25 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 20:29:25 DEBUG] [caching:24] Building activity cache...
[2022-11-22 20:29:25 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 20:29:25 INFO] [experiment:58] Validating the experiment's syntax
[2022-11-22 20:29:25 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 20:29:25 DEBUG] [secret:78] Loading secrets...
[2022-11-22 20:29:25 DEBUG] [secret:104] Done loading secrets
[2022-11-22 20:29:26 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-11-22 20:29:26 INFO] [experiment:109] Experiment looks valid
[2022-11-22 20:29:26 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 20:29:26 DEBUG] [caching:24] Building activity cache...
[2022-11-22 20:29:26 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 20:29:26 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 20:29:26 DEBUG] [secret:78] Loading secrets...
[2022-11-22 20:29:26 DEBUG] [secret:104] Done loading secrets
[2022-11-22 20:29:26 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-11-22 20:29:26 INFO] [run:320] Running experiment: A simple hello world experiment
[2022-11-22 20:29:26 DEBUG] [__init__:52] Initializing controls
[2022-11-22 20:29:26 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-11-22 20:29:26 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-11-22 20:29:26 INFO] [run:344] Steady-state strategy: default
[2022-11-22 20:29:26 INFO] [run:348] Rollbacks strategy: always
[2022-11-22 20:29:26 INFO] [run:353] No steady state hypothesis defined. That's ok, just exploring.
[2022-11-22 20:29:26 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-11-22 20:29:26 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-11-22 20:29:26 INFO] [run:607] Playing your experiment's method now...
[2022-11-22 20:29:26 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-11-22 20:29:26 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-11-22 20:29:26 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-11-22 20:29:26 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-11-22 20:29:26 INFO] [activity:204] Action: dis-bonjour
[2022-11-22 20:29:26 DEBUG] [process:52] Running: /usr/bin/echo Bonjour !
[2022-11-22 20:29:26 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'Bonjour !\n', 'stderr': ''}'
[2022-11-22 20:29:26 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-11-22 20:29:26 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-11-22 20:29:26 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-11-22 20:29:26 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-11-22 20:29:26 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-11-22 20:29:26 INFO] [run:893] Let's rollback...
[2022-11-22 20:29:26 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-11-22 20:29:26 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-11-22 20:29:26 INFO] [rollback:27] No declared rollbacks, let's move on.
[2022-11-22 20:29:26 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-11-22 20:29:26 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-11-22 20:29:26 INFO] [run:458] Experiment ended with status: completed
[2022-11-22 20:29:26 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-11-22 20:29:26 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2022-11-22 20:29:26 DEBUG] [__init__:38] Reliably client TLS verification: True
[2022-11-22 20:29:26 DEBUG] [__init__:39] Reliably client scheme: https
[2022-11-22 20:29:26 DEBUG] [experiment:77] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/58397051-3da8-488c-9312-eccf388fe7cf/executions: 201
[2022-11-22 20:29:26 DEBUG] [__init__:91] Cleaning up controls
[2022-11-22 20:29:26 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-11-22 20:29:26 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-11-22 20:29:26 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 20:43:34 DEBUG] [cli:112] ###############################################################################
[2022-11-22 20:43:34 DEBUG] [cli:113] Running command 'run'
[2022-11-22 20:43:34 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-11-22 20:43:34 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-11-22 20:43:34 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 20:43:35 DEBUG] [loader:129] Fetched experiment: 
    {"title":"A simple hello world experiment","method":[{"name":"dis-bonjour","type":"action","provider":{"path":"echo","type":"process","arguments":"${message}"}}],"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"58397051-3da8-488c-9312-eccf388fe7cf","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"n/a","configuration":{"message":"Bonjour !"}}
[2022-11-22 20:43:35 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 20:43:35 DEBUG] [caching:24] Building activity cache...
[2022-11-22 20:43:35 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 20:43:35 INFO] [experiment:58] Validating the experiment's syntax
[2022-11-22 20:43:35 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 20:43:35 DEBUG] [secret:78] Loading secrets...
[2022-11-22 20:43:35 DEBUG] [secret:104] Done loading secrets
[2022-11-22 20:43:35 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-11-22 20:43:35 INFO] [experiment:109] Experiment looks valid
[2022-11-22 20:43:35 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 20:43:35 DEBUG] [caching:24] Building activity cache...
[2022-11-22 20:43:35 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 20:43:35 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 20:43:35 DEBUG] [secret:78] Loading secrets...
[2022-11-22 20:43:35 DEBUG] [secret:104] Done loading secrets
[2022-11-22 20:43:35 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-11-22 20:43:35 INFO] [run:320] Running experiment: A simple hello world experiment
[2022-11-22 20:43:35 DEBUG] [__init__:52] Initializing controls
[2022-11-22 20:43:35 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-11-22 20:43:35 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-11-22 20:43:35 INFO] [run:344] Steady-state strategy: default
[2022-11-22 20:43:35 INFO] [run:348] Rollbacks strategy: always
[2022-11-22 20:43:35 INFO] [run:353] No steady state hypothesis defined. That's ok, just exploring.
[2022-11-22 20:43:35 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-11-22 20:43:35 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-11-22 20:43:35 INFO] [run:607] Playing your experiment's method now...
[2022-11-22 20:43:35 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-11-22 20:43:35 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-11-22 20:43:35 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-11-22 20:43:35 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-11-22 20:43:35 INFO] [activity:204] Action: dis-bonjour
[2022-11-22 20:43:35 DEBUG] [process:52] Running: /usr/bin/echo Bonjour !
[2022-11-22 20:43:35 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'Bonjour !\n', 'stderr': ''}'
[2022-11-22 20:43:35 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-11-22 20:43:35 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-11-22 20:43:35 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-11-22 20:43:35 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-11-22 20:43:35 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-11-22 20:43:35 INFO] [run:893] Let's rollback...
[2022-11-22 20:43:35 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-11-22 20:43:35 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-11-22 20:43:35 INFO] [rollback:27] No declared rollbacks, let's move on.
[2022-11-22 20:43:35 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-11-22 20:43:35 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-11-22 20:43:35 INFO] [run:458] Experiment ended with status: completed
[2022-11-22 20:43:35 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-11-22 20:43:35 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2022-11-22 20:43:35 DEBUG] [__init__:38] Reliably client TLS verification: True
[2022-11-22 20:43:35 DEBUG] [__init__:39] Reliably client scheme: https
[2022-11-22 20:43:35 DEBUG] [experiment:77] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/58397051-3da8-488c-9312-eccf388fe7cf/executions: 201
[2022-11-22 20:43:35 DEBUG] [__init__:91] Cleaning up controls
[2022-11-22 20:43:35 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-11-22 20:43:35 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-11-22 20:43:35 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 21:46:36 DEBUG] [cli:112] ###############################################################################
[2022-11-22 21:46:36 DEBUG] [cli:113] Running command 'run'
[2022-11-22 21:46:36 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-11-22 21:46:37 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-11-22 21:46:37 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 21:46:37 DEBUG] [loader:129] Fetched experiment: 
    {"title":"A simple hello world experiment","method":[{"name":"dis-bonjour","type":"action","provider":{"path":"echo","type":"process","arguments":"${message}"}}],"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"58397051-3da8-488c-9312-eccf388fe7cf","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"n/a","configuration":{"message":"Bonjour !"}}
[2022-11-22 21:46:37 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 21:46:37 DEBUG] [caching:24] Building activity cache...
[2022-11-22 21:46:37 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 21:46:37 INFO] [experiment:58] Validating the experiment's syntax
[2022-11-22 21:46:37 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 21:46:37 DEBUG] [secret:78] Loading secrets...
[2022-11-22 21:46:37 DEBUG] [secret:104] Done loading secrets
[2022-11-22 21:46:37 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-11-22 21:46:37 INFO] [experiment:109] Experiment looks valid
[2022-11-22 21:46:37 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 21:46:37 DEBUG] [caching:24] Building activity cache...
[2022-11-22 21:46:37 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 21:46:37 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 21:46:37 DEBUG] [secret:78] Loading secrets...
[2022-11-22 21:46:37 DEBUG] [secret:104] Done loading secrets
[2022-11-22 21:46:37 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-11-22 21:46:37 INFO] [run:320] Running experiment: A simple hello world experiment
[2022-11-22 21:46:37 DEBUG] [__init__:52] Initializing controls
[2022-11-22 21:46:37 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-11-22 21:46:37 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-11-22 21:46:37 INFO] [run:344] Steady-state strategy: default
[2022-11-22 21:46:37 INFO] [run:348] Rollbacks strategy: always
[2022-11-22 21:46:37 INFO] [run:353] No steady state hypothesis defined. That's ok, just exploring.
[2022-11-22 21:46:37 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-11-22 21:46:37 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-11-22 21:46:37 INFO] [run:607] Playing your experiment's method now...
[2022-11-22 21:46:37 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-11-22 21:46:37 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-11-22 21:46:37 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-11-22 21:46:37 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-11-22 21:46:37 INFO] [activity:204] Action: dis-bonjour
[2022-11-22 21:46:37 DEBUG] [process:52] Running: /usr/bin/echo Bonjour !
[2022-11-22 21:46:37 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'Bonjour !\n', 'stderr': ''}'
[2022-11-22 21:46:37 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-11-22 21:46:37 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-11-22 21:46:37 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-11-22 21:46:37 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-11-22 21:46:37 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-11-22 21:46:37 INFO] [run:893] Let's rollback...
[2022-11-22 21:46:37 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-11-22 21:46:37 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-11-22 21:46:37 INFO] [rollback:27] No declared rollbacks, let's move on.
[2022-11-22 21:46:37 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-11-22 21:46:37 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-11-22 21:46:37 INFO] [run:458] Experiment ended with status: completed
[2022-11-22 21:46:37 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-11-22 21:46:37 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2022-11-22 21:46:37 DEBUG] [__init__:38] Reliably client TLS verification: True
[2022-11-22 21:46:37 DEBUG] [__init__:39] Reliably client scheme: https
[2022-11-22 21:46:38 DEBUG] [experiment:77] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/58397051-3da8-488c-9312-eccf388fe7cf/executions: 201
[2022-11-22 21:46:38 DEBUG] [__init__:91] Cleaning up controls
[2022-11-22 21:46:38 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-11-22 21:46:38 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-11-22 21:46:38 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 21:59:33 DEBUG] [cli:112] ###############################################################################
[2022-11-22 21:59:33 DEBUG] [cli:113] Running command 'run'
[2022-11-22 21:59:33 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-11-22 21:59:33 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-11-22 21:59:33 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 21:59:33 DEBUG] [loader:129] Fetched experiment: 
    {"title":"A simple hello world experiment","method":[{"name":"dis-bonjour","type":"action","provider":{"path":"echo","type":"process","arguments":"${message}"}}],"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"58397051-3da8-488c-9312-eccf388fe7cf","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"n/a","configuration":{"message":"Bonjour !"}}
[2022-11-22 21:59:33 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 21:59:33 DEBUG] [caching:24] Building activity cache...
[2022-11-22 21:59:33 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 21:59:33 INFO] [experiment:58] Validating the experiment's syntax
[2022-11-22 21:59:33 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 21:59:33 DEBUG] [secret:78] Loading secrets...
[2022-11-22 21:59:33 DEBUG] [secret:104] Done loading secrets
[2022-11-22 21:59:33 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-11-22 21:59:33 INFO] [experiment:109] Experiment looks valid
[2022-11-22 21:59:33 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 21:59:33 DEBUG] [caching:24] Building activity cache...
[2022-11-22 21:59:33 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 21:59:33 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 21:59:33 DEBUG] [secret:78] Loading secrets...
[2022-11-22 21:59:33 DEBUG] [secret:104] Done loading secrets
[2022-11-22 21:59:33 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-11-22 21:59:33 INFO] [run:320] Running experiment: A simple hello world experiment
[2022-11-22 21:59:33 DEBUG] [__init__:52] Initializing controls
[2022-11-22 21:59:33 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-11-22 21:59:33 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-11-22 21:59:33 INFO] [run:344] Steady-state strategy: default
[2022-11-22 21:59:33 INFO] [run:348] Rollbacks strategy: always
[2022-11-22 21:59:33 INFO] [run:353] No steady state hypothesis defined. That's ok, just exploring.
[2022-11-22 21:59:33 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-11-22 21:59:33 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-11-22 21:59:33 INFO] [run:607] Playing your experiment's method now...
[2022-11-22 21:59:33 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-11-22 21:59:33 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-11-22 21:59:33 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-11-22 21:59:33 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-11-22 21:59:33 INFO] [activity:204] Action: dis-bonjour
[2022-11-22 21:59:33 DEBUG] [process:52] Running: /usr/bin/echo Bonjour !
[2022-11-22 21:59:33 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'Bonjour !\n', 'stderr': ''}'
[2022-11-22 21:59:33 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-11-22 21:59:33 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-11-22 21:59:33 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-11-22 21:59:33 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-11-22 21:59:33 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-11-22 21:59:33 INFO] [run:893] Let's rollback...
[2022-11-22 21:59:33 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-11-22 21:59:33 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-11-22 21:59:33 INFO] [rollback:27] No declared rollbacks, let's move on.
[2022-11-22 21:59:33 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-11-22 21:59:33 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-11-22 21:59:33 INFO] [run:458] Experiment ended with status: completed
[2022-11-22 21:59:33 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-11-22 21:59:33 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2022-11-22 21:59:33 DEBUG] [__init__:38] Reliably client TLS verification: True
[2022-11-22 21:59:33 DEBUG] [__init__:39] Reliably client scheme: https
[2022-11-22 21:59:34 DEBUG] [experiment:77] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/58397051-3da8-488c-9312-eccf388fe7cf/executions: 201
[2022-11-22 21:59:34 DEBUG] [__init__:91] Cleaning up controls
[2022-11-22 21:59:34 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-11-22 21:59:34 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-11-22 21:59:34 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 22:26:54 DEBUG] [cli:112] ###############################################################################
[2022-11-22 22:26:54 DEBUG] [cli:113] Running command 'run'
[2022-11-22 22:26:54 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-11-22 22:26:54 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-11-22 22:26:54 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 22:27:05 DEBUG] [loader:129] Fetched experiment: 
    {"title":"A simple hello world experiment","method":[{"name":"dis-bonjour","type":"action","provider":{"path":"echo","type":"process","arguments":"${message}"}}],"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"58397051-3da8-488c-9312-eccf388fe7cf","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"n/a","configuration":{"message":"Bonjour !"}}
[2022-11-22 22:27:05 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-11-22 22:27:05 DEBUG] [caching:24] Building activity cache...
[2022-11-22 22:27:05 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 22:27:05 INFO] [experiment:58] Validating the experiment's syntax
[2022-11-22 22:27:05 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 22:27:05 DEBUG] [secret:78] Loading secrets...
[2022-11-22 22:27:05 DEBUG] [secret:104] Done loading secrets
[2022-11-22 22:27:05 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-11-22 22:27:05 INFO] [experiment:109] Experiment looks valid
[2022-11-22 22:27:05 DEBUG] [caching:42] Clearing activities cache
[2022-11-22 22:27:05 DEBUG] [caching:24] Building activity cache...
[2022-11-22 22:27:05 DEBUG] [caching:35] Cached 1 activities
[2022-11-22 22:27:05 DEBUG] [configuration:63] Loading configuration...
[2022-11-22 22:27:05 DEBUG] [secret:78] Loading secrets...
[2022-11-22 22:27:05 DEBUG] [secret:104] Done loading secrets
[2022-11-22 22:27:05 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-11-22 22:27:05 INFO] [run:320] Running experiment: A simple hello world experiment
[2022-11-22 22:27:05 DEBUG] [__init__:52] Initializing controls
[2022-11-22 22:27:05 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-11-22 22:27:05 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-11-22 22:27:05 INFO] [run:344] Steady-state strategy: default
[2022-11-22 22:27:05 INFO] [run:348] Rollbacks strategy: always
[2022-11-22 22:27:05 INFO] [run:353] No steady state hypothesis defined. That's ok, just exploring.
[2022-11-22 22:27:05 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-11-22 22:27:05 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-11-22 22:27:05 INFO] [run:607] Playing your experiment's method now...
[2022-11-22 22:27:05 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-11-22 22:27:05 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-11-22 22:27:05 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-11-22 22:27:05 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-11-22 22:27:05 INFO] [activity:204] Action: dis-bonjour
[2022-11-22 22:27:05 DEBUG] [process:52] Running: /usr/bin/echo Bonjour !
[2022-11-22 22:27:05 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'Bonjour !\n', 'stderr': ''}'
[2022-11-22 22:27:05 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-11-22 22:27:05 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-11-22 22:27:05 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-11-22 22:27:05 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-11-22 22:27:05 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-11-22 22:27:05 INFO] [run:893] Let's rollback...
[2022-11-22 22:27:05 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-11-22 22:27:05 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-11-22 22:27:05 INFO] [rollback:27] No declared rollbacks, let's move on.
[2022-11-22 22:27:05 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-11-22 22:27:05 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-11-22 22:27:05 INFO] [run:458] Experiment ended with status: completed
[2022-11-22 22:27:05 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-11-22 22:27:05 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2022-11-22 22:27:05 DEBUG] [__init__:38] Reliably client TLS verification: True
[2022-11-22 22:27:05 DEBUG] [__init__:39] Reliably client scheme: https
[2022-11-22 22:27:06 DEBUG] [experiment:77] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/58397051-3da8-488c-9312-eccf388fe7cf/executions: 201
[2022-11-22 22:27:06 DEBUG] [__init__:91] Cleaning up controls
[2022-11-22 22:27:06 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-11-22 22:27:06 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-11-22 22:27:06 DEBUG] [caching:42] Clearing activities cache
