[2023-02-08 16:17:43 DEBUG] [cli:115] ###############################################################################
[2023-02-08 16:17:43 DEBUG] [cli:116] Running command 'run'
[2023-02-08 16:17:43 DEBUG] [cli:120] Using settings file '/home/runner/.config/reliably/plans/3d5ee652-aaf4-4f49-b01c-223c513c73ac/ctk.yaml'
[2023-02-08 16:17:43 DEBUG] [__init__:243] Loading global control 'reliably-integration-slack' from /home/runner/.config/reliably/plans/3d5ee652-aaf4-4f49-b01c-223c513c73ac/controls/f5647a66-9c5b-4bef-a801-821864c2e8e1.json
[2023-02-08 16:17:43 DEBUG] [__init__:243] Loading global control 'reliably-integration-opentelemetry' from /home/runner/.config/reliably/plans/3d5ee652-aaf4-4f49-b01c-223c513c73ac/controls/b9df4af2-0719-405a-b732-41b7496b1de7.json
[2023-02-08 16:17:44 DEBUG] [__init__:459] Applying before-control 'reliably-integration-slack' on 'loader'
[2023-02-08 16:17:44 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosslack/control.py' does not declare 'before_loading_experiment_control'
[2023-02-08 16:17:44 DEBUG] [__init__:459] Applying before-control 'reliably-integration-opentelemetry' on 'loader'
[2023-02-08 16:17:44 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaostracing/oltp.py' does not declare 'before_loading_experiment_control'
[2023-02-08 16:17:44 DEBUG] [loader:129] Fetched experiment: 
    {"title":"SLO error-count-3h / Error budget 10%","method":[],"runtime":{"hypothesis":{"strategy":"after-method-only"}},"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"b27b5d0a-aaf2-4213-aa66-019a198ec52e","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"Monitor the health of our demo service from our users perspective and ensure they have a high-quality experience","contributions":{"quality":"medium","security":"none","performance":"low","availability":"high"},"steady-state-hypothesis":{"title":"Compute SLO and validate its Error Budget with our target","probes":[{"name":"get-slo","type":"probe","provider":{"func":"compute_slo","type":"python","module":"chaosreliably.activities.slo.probes","arguments":{"slo":{"kind":"ServiceLevelObjective","spec":{"goal":0.9,"method":"good_bad_ratio","backend":"cloud_monitoring_mql","exporters":[],"description":"Availability of Cloud Run service","service_level_indicator":{"filter_good":"fetch cloud_run_revision | metric 'run.googleapis.com/request_count' | filter resource.project_id == '${CLOUDRUN_PROJECT_ID}' | filter resource.service_name == '${CLOUDRUN_SERVICE_NAME}' | filter metric.response_code_class == '2xx'","filter_valid":"fetch cloud_run_revision | metric 'run.googleapis.com/request_count' | filter resource.project_id == '${CLOUDRUN_PROJECT_ID}' | filter resource.service_name == '${CLOUDRUN_SERVICE_NAME}'"}},"metadata":{"name":"cloudrun-service-availability","labels":{"slo_name":"availability","feature_name":"service","service_name":"cloudrun"}},"apiVersion":"sre.google.com/v2"},"config":{"backends":{"cloud_monitoring_mql":{"project_id":"${STACKDRIVER_HOST_PROJECT_ID}"}},"error_budget_policies":{"default":{"steps":[{"name":"3 hours","alert":false,"window":10800,"message_ok":"Last 3 hours on track","message_alert":"Page the SRE team to defend the SLO","burn_rate_threshold":9}]}}}}},"tolerance":{"name":"there-should-be-error-budget-left","type":"probe","provider":{"func":"has_error_budget_left","type":"python","module":"chaosreliably.activities.slo.tolerances","arguments":{"name":"cloudrun-service-availability"}}}}]}}
[2023-02-08 16:17:44 DEBUG] [__init__:459] Applying after-control 'reliably-integration-slack' on 'loader'
[2023-02-08 16:17:44 DEBUG] [python:196] Control 'after_loading_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2023-02-08 16:17:44 DEBUG] [__init__:459] Applying after-control 'reliably-integration-opentelemetry' on 'loader'
[2023-02-08 16:17:44 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaostracing/oltp.py' does not declare 'after_loading_experiment_control'
[2023-02-08 16:17:44 DEBUG] [caching:24] Building activity cache...
[2023-02-08 16:17:44 DEBUG] [caching:35] Cached 1 activities
[2023-02-08 16:17:44 INFO] [experiment:58] Validating the experiment's syntax
[2023-02-08 16:17:44 DEBUG] [configuration:63] Loading configuration...
[2023-02-08 16:17:44 DEBUG] [secret:78] Loading secrets...
[2023-02-08 16:17:44 DEBUG] [secret:104] Done loading secrets
[2023-02-08 16:17:45 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2023-02-08 16:17:45 INFO] [experiment:109] Experiment looks valid
[2023-02-08 16:17:45 DEBUG] [caching:42] Clearing activities cache
[2023-02-08 16:17:45 DEBUG] [cli:314] Runtime strategies: hypothesis - after-method-only / rollbacks - default
[2023-02-08 16:17:45 DEBUG] [caching:24] Building activity cache...
[2023-02-08 16:17:45 DEBUG] [caching:35] Cached 1 activities
[2023-02-08 16:17:45 DEBUG] [configuration:63] Loading configuration...
[2023-02-08 16:17:45 DEBUG] [secret:78] Loading secrets...
[2023-02-08 16:17:45 DEBUG] [secret:104] Done loading secrets
[2023-02-08 16:17:45 DEBUG] [configuration:160] Loading dynamic configuration...
[2023-02-08 16:17:45 INFO] [run:370] Running experiment: SLO error-count-3h / Error budget 10%
[2023-02-08 16:17:45 DEBUG] [__init__:171] Initializing global control 'reliably-integration-slack'
[2023-02-08 16:17:45 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosslack/control.py' does not declare 'configure_control'
[2023-02-08 16:17:45 DEBUG] [__init__:171] Initializing global control 'reliably-integration-opentelemetry'
[2023-02-08 16:17:45 DEBUG] [python:196] Control 'configure_control' loaded from '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaostracing/oltp.py'
[2023-02-08 16:17:45 INFO] [oltp:365] Chaos Toolkit Open Telemetry tracer created
[2023-02-08 16:17:45 DEBUG] [__init__:64] Initializing controls
[2023-02-08 16:17:45 DEBUG] [__init__:73] Initializing control 'reliably'
[2023-02-08 16:17:45 DEBUG] [python:196] Control 'configure_control' loaded from '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2023-02-08 16:17:45 DEBUG] [experiment:402] Configure Reliably's experiment control
[2023-02-08 16:17:45 INFO] [experiment:188] Reliably execution: 9110c0e4-d4e4-46f6-a13e-e27f69bf81a0
[2023-02-08 16:17:46 DEBUG] [experiment:74] Starting Reliably state checker now
[2023-02-08 16:17:46 INFO] [run:397] Steady-state strategy: after-method-only
[2023-02-08 16:17:46 INFO] [run:401] Rollbacks strategy: default
[2023-02-08 16:17:46 DEBUG] [__init__:459] Applying before-control 'reliably' on 'experiment'
[2023-02-08 16:17:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2023-02-08 16:17:46 DEBUG] [__init__:459] Applying before-control 'reliably-integration-slack' on 'experiment'
[2023-02-08 16:17:46 DEBUG] [python:196] Control 'before_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2023-02-08 16:17:46 DEBUG] [__init__:459] Applying before-control 'reliably-integration-opentelemetry' on 'experiment'
[2023-02-08 16:17:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaostracing/oltp.py' does not declare 'before_experiment_control'
[2023-02-08 16:17:46 INFO] [run:664] Playing your experiment's method now...
[2023-02-08 16:17:46 DEBUG] [__init__:459] Applying before-control 'reliably' on 'method'
[2023-02-08 16:17:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2023-02-08 16:17:46 INFO] [activity:133] No declared activities, let's move on.
[2023-02-08 16:17:46 DEBUG] [__init__:459] Applying after-control 'reliably' on 'method'
[2023-02-08 16:17:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2023-02-08 16:17:46 DEBUG] [run:591] Running steady-state hypothesis after the method
[2023-02-08 16:17:46 INFO] [hypothesis:186] Steady state hypothesis: Compute SLO and validate its Error Budget with our target
[2023-02-08 16:17:46 DEBUG] [__init__:459] Applying before-control 'reliably' on 'hypothesis'
[2023-02-08 16:17:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-02-08 16:17:46 DEBUG] [__init__:459] Applying before-control 'reliably' on 'hypothesis'
[2023-02-08 16:17:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-02-08 16:17:46 DEBUG] [__init__:459] Applying before-control 'reliably-integration-slack' on 'hypothesis'
[2023-02-08 16:17:46 DEBUG] [python:196] Control 'before_hypothesis_control' loaded from '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2023-02-08 16:17:46 DEBUG] [__init__:459] Applying before-control 'reliably-integration-opentelemetry' on 'hypothesis'
[2023-02-08 16:17:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaostracing/oltp.py' does not declare 'before_hypothesis_control'
[2023-02-08 16:17:46 DEBUG] [__init__:459] Applying before-control 'reliably' on 'activity'
[2023-02-08 16:17:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-02-08 16:17:46 DEBUG] [__init__:459] Applying before-control 'reliably' on 'activity'
[2023-02-08 16:17:46 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-02-08 16:17:46 DEBUG] [__init__:459] Applying before-control 'reliably-integration-slack' on 'activity'
[2023-02-08 16:17:46 DEBUG] [python:196] Control 'before_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2023-02-08 16:17:47 DEBUG] [__init__:459] Applying before-control 'reliably-integration-opentelemetry' on 'activity'
[2023-02-08 16:17:47 DEBUG] [python:196] Control 'before_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaostracing/oltp.py'
[2023-02-08 16:17:47 INFO] [activity:215] Probe: get-slo
[2023-02-08 16:17:47 DEBUG] [python:33] Activity 'get-slo' loaded from '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/activities/slo/probes.py'
[2023-02-08 16:17:47 DEBUG] [report:212] cloudrun-service-availability    | 3 hours  | Using backend CloudMonitoringMql.good_bad_ratio (from SLO config file).
[2023-02-08 16:17:48 DEBUG] [cloud_monitoring_mql:222] [point_data {
      values {
        int64_value: 16884
      }
      time_interval {
        end_time {
          seconds: 1675873067
        }
        start_time {
          seconds: 1675862267
          nanos: 999000
        }
      }
    }
    ]
[2023-02-08 16:17:48 DEBUG] [cloud_monitoring_mql:222] [point_data {
      values {
        int64_value: 16900
      }
      time_interval {
        end_time {
          seconds: 1675873067
        }
        start_time {
          seconds: 1675862267
          nanos: 999000
        }
      }
    }
    ]
[2023-02-08 16:17:48 DEBUG] [cloud_monitoring_mql:94] Good events: 16884 | Bad events: 16
[2023-02-08 16:17:48 DEBUG] [report:226] cloudrun-service-availability    | 3 hours  | Backend response: (16884, 16)
[2023-02-08 16:17:48 DEBUG] [report:139] cloudrun-service-availability    | 3 hours  | SLO report starting ...
[2023-02-08 16:17:48 DEBUG] [report:257] cloudrun-service-availability    | 3 hours  | Good: 16884 | Bad: 16
[2023-02-08 16:17:48 INFO] [compute:87] cloudrun-service-availability    | 3 hours  | SLI: 99.9053 % | SLO: 90.0 % | Gap: +9.91 % | BR: 0.0 / 9.0 | Alert: 0 | Good: 16884    | Bad: 16      
[2023-02-08 16:17:48 DEBUG] [compute:94] [{'alert': False,
      'backend': 'cloud_monitoring_mql',
      'bad_events_count': 16,
      'consequence_message': 'Last 3 hours on track',
      'description': 'Availability of Cloud Run service',
      'error_budget_burn_rate': 0.0,
      'error_budget_burn_rate_threshold': 9.0,
      'error_budget_measurement': 0.0009470000000000312,
      'error_budget_minutes': 17.999999999999996,
      'error_budget_policy': 'default',
      'error_budget_policy_step_name': '3 hours',
      'error_budget_remaining_minutes': 17.82953999999999,
      'error_budget_target': 0.09999999999999998,
      'error_minutes': 0.1704600000000056,
      'errors': [],
      'events_count': 16900,
      'exporters': [],
      'gap': 0.09905299999999995,
      'goal': 0.9,
      'good_events_count': 16884,
      'metadata': {'labels': {'feature_name': 'service',
                              'service_name': 'cloudrun',
                              'slo_name': 'availability'},
                   'name': 'cloudrun-service-availability'},
      'name': 'cloudrun-service-availability',
      'sli_measurement': 0.999053,
      'timestamp': 1675873067,
      'timestamp_human': '2023-02-08T16:17:47.449788+00:00',
      'valid': True,
      'window': 10800}]
[2023-02-08 16:17:48 INFO] [compute:95] Run finished successfully in 1.0s.
[2023-02-08 16:17:48 DEBUG] [activity:235]   => succeeded with '[{'name': 'cloudrun-service-availability', 'description': 'Availability of Cloud Run service', 'goal': 0.9, 'backend': 'cloud_monitoring_mql', 'gap': 0.09905299999999995, 'error_budget_policy_step_name': '3 hours', 'error_budget_target': 0.09999999999999998, 'error_budget_measurement': 0.0009470000000000312, 'error_budget_burn_rate': 0.0, 'error_budget_burn_rate_threshold': 9.0, 'error_budget_minutes': 17.999999999999996, 'error_budget_remaining_minutes': 17.82953999999999, 'error_minutes': 0.1704600000000056, 'valid': True, 'timestamp': 1675873067, 'timestamp_human': '2023-02-08T16:17:47.449788+00:00', 'window': 10800, 'alert': False, 'consequence_message': 'Last 3 hours on track', 'exporters': [], 'error_budget_policy': 'default', 'sli_measurement': 0.999053, 'events_count': 16900, 'bad_events_count': 16, 'good_events_count': 16884, 'metadata': {'name': 'cloudrun-service-availability', 'labels': {'slo_name': 'availability', 'feature_name': 'service', 'service_name': 'cloudrun'}}, 'errors': []}]'
[2023-02-08 16:17:48 DEBUG] [__init__:459] Applying after-control 'reliably' on 'activity'
[2023-02-08 16:17:48 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-02-08 16:17:48 DEBUG] [__init__:459] Applying after-control 'reliably' on 'activity'
[2023-02-08 16:17:48 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-02-08 16:17:48 DEBUG] [__init__:459] Applying after-control 'reliably-integration-slack' on 'activity'
[2023-02-08 16:17:48 DEBUG] [python:196] Control 'after_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2023-02-08 16:17:49 DEBUG] [__init__:459] Applying after-control 'reliably-integration-opentelemetry' on 'activity'
[2023-02-08 16:17:49 DEBUG] [python:196] Control 'after_activity_control' loaded from '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaostracing/oltp.py'
[2023-02-08 16:17:49 DEBUG] [hypothesis:226] allowed tolerance is {'name': 'there-should-be-error-budget-left', 'type': 'probe', 'provider': {'func': 'has_error_budget_left', 'type': 'python', 'module': 'chaosreliably.activities.slo.tolerances', 'arguments': {'name': 'cloudrun-service-availability'}}}
[2023-02-08 16:17:49 DEBUG] [python:33] Activity 'there-should-be-error-budget-left' loaded from '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/activities/slo/tolerances.py'
[2023-02-08 16:17:49 INFO] [hypothesis:236] Steady state hypothesis is met!
[2023-02-08 16:17:49 DEBUG] [__init__:459] Applying after-control 'reliably' on 'hypothesis'
[2023-02-08 16:17:49 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-02-08 16:17:49 DEBUG] [__init__:459] Applying after-control 'reliably' on 'hypothesis'
[2023-02-08 16:17:49 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-02-08 16:17:49 DEBUG] [__init__:459] Applying after-control 'reliably-integration-slack' on 'hypothesis'
[2023-02-08 16:17:49 DEBUG] [python:196] Control 'after_hypothesis_control' loaded from '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2023-02-08 16:17:49 DEBUG] [__init__:459] Applying after-control 'reliably-integration-opentelemetry' on 'hypothesis'
[2023-02-08 16:17:49 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaostracing/oltp.py' does not declare 'after_hypothesis_control'
[2023-02-08 16:17:49 INFO] [run:944] Let's rollback...
[2023-02-08 16:17:49 DEBUG] [__init__:459] Applying before-control 'reliably' on 'rollback'
[2023-02-08 16:17:49 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2023-02-08 16:17:49 INFO] [rollback:31] No declared rollbacks, let's move on.
[2023-02-08 16:17:49 DEBUG] [__init__:459] Applying after-control 'reliably' on 'rollback'
[2023-02-08 16:17:49 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2023-02-08 16:17:49 INFO] [run:511] Experiment ended with status: completed
[2023-02-08 16:17:49 DEBUG] [__init__:459] Applying after-control 'reliably' on 'experiment'
[2023-02-08 16:17:49 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_experiment_control'
[2023-02-08 16:17:49 DEBUG] [__init__:459] Applying after-control 'reliably-integration-slack' on 'experiment'
[2023-02-08 16:17:49 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosslack/control.py'
[2023-02-08 16:17:50 DEBUG] [__init__:459] Applying after-control 'reliably-integration-opentelemetry' on 'experiment'
[2023-02-08 16:17:50 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaostracing/oltp.py' does not declare 'after_experiment_control'
[2023-02-08 16:17:50 DEBUG] [__init__:103] Cleaning up controls
[2023-02-08 16:17:50 DEBUG] [__init__:112] Cleaning up control 'reliably'
[2023-02-08 16:17:50 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2023-02-08 16:17:50 DEBUG] [__init__:265] Cleaning up global control 'reliably-integration-slack'
[2023-02-08 16:17:50 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosslack/control.py' does not declare 'cleanup_control'
[2023-02-08 16:17:50 DEBUG] [__init__:265] Cleaning up global control 'reliably-integration-opentelemetry'
[2023-02-08 16:17:50 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaostracing/oltp.py' does not declare 'cleanup_control'
[2023-02-08 16:17:50 INFO] [experiment:236] Finishing Reliably execution...
[2023-02-08 16:17:50 DEBUG] [experiment:156] Stopping Reliably state checker now
[2023-02-08 16:17:51 INFO] [experiment:289] Finished Reliably execution. Bye!
[2023-02-08 16:17:51 DEBUG] [caching:42] Clearing activities cache
