[2023-04-05T11:26:04.251602+00:00 INFO] [plan:194] ################################################################################
[2023-04-05T11:26:04.251772+00:00 INFO] [plan:195] Starting Reliably experiment: https://app.reliably.dev/api/v1/organization/53c4af8a-6385-4a6a-891d-4286fb3cb8d8/experiments/c71acf34-63ac-46e3-bcc7-d5f2a556a43c/raw
[2023-04-05T11:26:04.252380+00:00 DEBUG] [__init__:206] Loading global control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b'
[2023-04-05T11:26:04.563096+00:00 DEBUG] [caching:24] Building activity cache...
[2023-04-05T11:26:04.563269+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-04-05T11:26:04.563393+00:00 INFO] [experiment:58] Validating the experiment's syntax
[2023-04-05T11:26:04.563457+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-04-05T11:26:04.563519+00:00 DEBUG] [secret:78] Loading secrets...
[2023-04-05T11:26:04.563584+00:00 DEBUG] [secret:103] Done loading secrets
[2023-04-05T11:26:04.589182+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2023-04-05T11:26:04.589302+00:00 INFO] [experiment:109] Experiment looks valid
[2023-04-05T11:26:04.589352+00:00 DEBUG] [caching:42] Clearing activities cache
[2023-04-05T11:26:04.589410+00:00 DEBUG] [caching:24] Building activity cache...
[2023-04-05T11:26:04.589453+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-04-05T11:26:04.589562+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-04-05T11:26:04.589613+00:00 DEBUG] [secret:78] Loading secrets...
[2023-04-05T11:26:04.589655+00:00 DEBUG] [secret:103] Done loading secrets
[2023-04-05T11:26:04.589698+00:00 DEBUG] [configuration:160] Loading dynamic configuration...
[2023-04-05T11:26:04.589798+00:00 INFO] [run:369] Running experiment: Latency remains under 200ms
[2023-04-05T11:26:04.591853+00:00 DEBUG] [__init__:171] Initializing global control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b'
[2023-04-05T11:26:04.591976+00:00 DEBUG] [python:196] Control 'configure_control' loaded from '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py'
[2023-04-05T11:26:04.592129+00:00 DEBUG] [__init__:43] Missing URL for safeguard/precheck call
[2023-04-05T11:26:04.592188+00:00 DEBUG] [__init__:64] Initializing controls
[2023-04-05T11:26:04.592234+00:00 DEBUG] [__init__:73] Initializing control 'reliably'
[2023-04-05T11:26:04.592289+00:00 DEBUG] [python:196] Control 'configure_control' loaded from '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py'
[2023-04-05T11:26:04.592379+00:00 DEBUG] [experiment:410] Configure Reliably's experiment control
[2023-04-05T11:26:04.924704+00:00 INFO] [experiment:192] Reliably execution: bbaf0f3e-41de-40e5-bcb9-ba1b85e50e29
[2023-04-05T11:26:05.203033+00:00 DEBUG] [experiment:552] Sending plan '8082e30c-b004-4c22-ab71-d11ad07ce0cc' status: running
[2023-04-05T11:26:05.747177+00:00 DEBUG] [experiment:78] Starting Reliably state checker now
[2023-04-05T11:26:05.747359+00:00 INFO] [run:396] Steady-state strategy: after-method-only
[2023-04-05T11:26:05.749104+00:00 INFO] [run:400] Rollbacks strategy: always
[2023-04-05T11:26:05.749429+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'experiment'
[2023-04-05T11:26:05.749732+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2023-04-05T11:26:05.750050+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'experiment'
[2023-04-05T11:26:05.750361+00:00 DEBUG] [python:196] Control 'before_experiment_control' loaded from '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py'
[2023-04-05T11:26:05.750855+00:00 DEBUG] [__init__:484] Before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' failed
Traceback (most recent call last):
  File "/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaoslib/control/__init__.py", line 465, in apply_controls
    apply_python_control(
  File "/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaoslib/control/python.py", line 179, in apply_python_control
    func(context=context, **arguments)
  File "/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py", line 29, in before_experiment_control
    run_all(context, configuration, secrets)
  File "/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/__init__.py", line 193, in run_all
    (handler or proxy).start_all(experiment, configuration, secrets)
  File "/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/__init__.py", line 142, in start_all
    g.start(experiment, configuration, secrets)
  File "/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/__init__.py", line 77, in start
    self.probes,
    ^^^^^^^^^^^
AttributeError: 'ReliablySafeguardGuardian' object has no attribute 'probes'
[2023-04-05T11:26:05.752806+00:00 INFO] [run:663] Playing your experiment's method now...
[2023-04-05T11:26:05.756424+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'method'
[2023-04-05T11:26:05.756871+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2023-04-05T11:26:05.757318+00:00 INFO] [activity:133] No declared activities, let's move on.
[2023-04-05T11:26:05.757721+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'method'
[2023-04-05T11:26:05.758180+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2023-04-05T11:26:05.758569+00:00 DEBUG] [run:590] Running steady-state hypothesis after the method
[2023-04-05T11:26:05.758662+00:00 INFO] [hypothesis:186] Steady state hypothesis: capture-response-time-and-verify-it
[2023-04-05T11:26:05.758754+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'hypothesis'
[2023-04-05T11:26:05.758821+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-04-05T11:26:05.758875+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'hypothesis'
[2023-04-05T11:26:05.758930+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py' does not declare 'before_hypothesis_control'
[2023-04-05T11:26:05.759007+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'activity'
[2023-04-05T11:26:05.759065+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-04-05T11:26:05.759114+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'activity'
[2023-04-05T11:26:05.759169+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py' does not declare 'before_activity_control'
[2023-04-05T11:26:05.759231+00:00 INFO] [activity:215] Probe: measure-endpoint-response-time
[2023-04-05T11:26:06.217729+00:00 DEBUG] [python:33] Activity 'measure-endpoint-response-time' loaded from '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/activities/http/probes.py'
[2023-04-05T11:26:06.453326+00:00 DEBUG] [activity:235]   => succeeded with '0.152371'
[2023-04-05T11:26:06.709252+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'activity'
[2023-04-05T11:26:06.709777+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-04-05T11:26:06.710119+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'activity'
[2023-04-05T11:26:06.710272+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py' does not declare 'after_activity_control'
[2023-04-05T11:26:06.710350+00:00 DEBUG] [hypothesis:226] allowed tolerance is {'name': 'validate-response-time', 'type': 'probe', 'provider': {'func': 'response_time_must_be_under', 'type': 'python', 'module': 'chaosreliably.activities.http.tolerances', 'arguments': {'latency': '${reliably_latency}'}}}
[2023-04-05T11:26:06.710447+00:00 DEBUG] [python:33] Activity 'validate-response-time' loaded from '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/activities/http/tolerances.py'
[2023-04-05T11:26:06.710592+00:00 DEBUG] [tolerances:13] Verify that response time is under: 0.2
[2023-04-05T11:26:06.710657+00:00 INFO] [hypothesis:236] Steady state hypothesis is met!
[2023-04-05T11:26:06.710735+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'hypothesis'
[2023-04-05T11:26:06.710798+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-04-05T11:26:06.710850+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'hypothesis'
[2023-04-05T11:26:06.710905+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py' does not declare 'after_hypothesis_control'
[2023-04-05T11:26:06.710988+00:00 WARNING] [run:706] Rollbacks were explicitly requested to be played
[2023-04-05T11:26:06.711049+00:00 INFO] [run:943] Let's rollback...
[2023-04-05T11:26:06.711126+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'rollback'
[2023-04-05T11:26:06.711185+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2023-04-05T11:26:06.711238+00:00 INFO] [rollback:31] No declared rollbacks, let's move on.
[2023-04-05T11:26:06.711306+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'rollback'
[2023-04-05T11:26:06.711363+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2023-04-05T11:26:06.711432+00:00 INFO] [run:510] Experiment ended with status: completed
[2023-04-05T11:26:06.711489+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'experiment'
[2023-04-05T11:26:06.711544+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_experiment_control'
[2023-04-05T11:26:06.711594+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'experiment'
[2023-04-05T11:26:06.711646+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py' does not declare 'after_experiment_control'
[2023-04-05T11:26:06.711696+00:00 DEBUG] [__init__:103] Cleaning up controls
[2023-04-05T11:26:06.711753+00:00 DEBUG] [__init__:112] Cleaning up control 'reliably'
[2023-04-05T11:26:06.711808+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2023-04-05T11:26:06.711871+00:00 DEBUG] [__init__:265] Cleaning up global control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b'
[2023-04-05T11:26:06.711923+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py' does not declare 'cleanup_control'
[2023-04-05T11:26:06.711982+00:00 INFO] [experiment:245] Finishing Reliably execution...
[2023-04-05T11:26:06.712329+00:00 DEBUG] [experiment:160] Stopping Reliably state checker now
[2023-04-05T11:26:07.079517+00:00 DEBUG] [experiment:552] Sending plan '8082e30c-b004-4c22-ab71-d11ad07ce0cc' status: completed
[2023-04-05T11:26:07.717550+00:00 INFO] [experiment:298] Finished Reliably execution. Bye!
[2023-04-05T11:26:07.717908+00:00 DEBUG] [caching:42] Clearing activities cache
