[2022-09-20 20:59:28 DEBUG] [cli:112] ###############################################################################
[2022-09-20 20:59:28 DEBUG] [cli:113] Running command 'run'
[2022-09-20 20:59:28 DEBUG] [cli:117] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2022-09-20 20:59:28 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2022-09-20 20:59:28 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-09-20 20:59:28 DEBUG] [__init__:399] No controls to apply on 'loader'
[2022-09-20 20:59:28 DEBUG] [caching:24] Building activity cache...
[2022-09-20 20:59:28 DEBUG] [caching:35] Cached 2 activities
[2022-09-20 20:59:28 INFO] [experiment:58] Validating the experiment's syntax
[2022-09-20 20:59:28 DEBUG] [configuration:63] Loading configuration...
[2022-09-20 20:59:28 DEBUG] [secret:78] Loading secrets...
[2022-09-20 20:59:28 DEBUG] [secret:104] Done loading secrets
[2022-09-20 20:59:28 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2022-09-20 20:59:28 INFO] [experiment:109] Experiment looks valid
[2022-09-20 20:59:28 DEBUG] [caching:42] Clearing activities cache
[2022-09-20 20:59:28 DEBUG] [caching:24] Building activity cache...
[2022-09-20 20:59:28 DEBUG] [caching:35] Cached 2 activities
[2022-09-20 20:59:28 DEBUG] [configuration:63] Loading configuration...
[2022-09-20 20:59:28 DEBUG] [secret:78] Loading secrets...
[2022-09-20 20:59:28 DEBUG] [secret:104] Done loading secrets
[2022-09-20 20:59:28 DEBUG] [configuration:160] Loading dynamic configuration...
[2022-09-20 20:59:28 INFO] [run:320] Running experiment: A simple hello world experiment
[2022-09-20 20:59:28 DEBUG] [__init__:52] Initializing controls
[2022-09-20 20:59:28 DEBUG] [__init__:61] Initializing control 'reliably'
[2022-09-20 20:59:28 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'configure_control'
[2022-09-20 20:59:28 INFO] [run:344] Steady-state strategy: default
[2022-09-20 20:59:28 INFO] [run:348] Rollbacks strategy: always
[2022-09-20 20:59:28 DEBUG] [__init__:409] Applying before-control 'reliably' on 'experiment'
[2022-09-20 20:59:28 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2022-09-20 20:59:28 DEBUG] [run:506] Running steady-state hypothesis before the method
[2022-09-20 20:59:28 INFO] [hypothesis:182] Steady state hypothesis: Check we can say hello
[2022-09-20 20:59:28 DEBUG] [__init__:409] Applying before-control 'reliably' on 'hypothesis'
[2022-09-20 20:59:28 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2022-09-20 20:59:28 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-09-20 20:59:28 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-09-20 20:59:28 INFO] [activity:204] Probe: echo-hello
[2022-09-20 20:59:28 DEBUG] [process:52] Running: /usr/bin/echo hello boom
[2022-09-20 20:59:28 DEBUG] [__init__:157] Data encoding detected as 'ascii' with a confidence of 1.0
[2022-09-20 20:59:28 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'hello boom\n', 'stderr': ''}'
[2022-09-20 20:59:28 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-09-20 20:59:28 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-09-20 20:59:28 DEBUG] [hypothesis:221] allowed tolerance is 0
[2022-09-20 20:59:28 INFO] [hypothesis:231] Steady state hypothesis is met!
[2022-09-20 20:59:28 DEBUG] [__init__:409] Applying after-control 'reliably' on 'hypothesis'
[2022-09-20 20:59:28 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2022-09-20 20:59:28 INFO] [run:607] Playing your experiment's method now...
[2022-09-20 20:59:28 DEBUG] [__init__:409] Applying before-control 'reliably' on 'method'
[2022-09-20 20:59:28 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2022-09-20 20:59:28 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-09-20 20:59:28 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-09-20 20:59:28 INFO] [activity:204] Action: say-hello
[2022-09-20 20:59:28 DEBUG] [process:52] Running: /usr/bin/echo hello
[2022-09-20 20:59:28 DEBUG] [__init__:157] Data encoding detected as 'ascii' with a confidence of 1.0
[2022-09-20 20:59:28 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'hello\n', 'stderr': ''}'
[2022-09-20 20:59:28 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-09-20 20:59:28 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-09-20 20:59:28 DEBUG] [__init__:409] Applying after-control 'reliably' on 'method'
[2022-09-20 20:59:28 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2022-09-20 20:59:28 DEBUG] [run:536] Running steady-state hypothesis after the method
[2022-09-20 20:59:28 INFO] [hypothesis:182] Steady state hypothesis: Check we can say hello
[2022-09-20 20:59:28 DEBUG] [__init__:409] Applying before-control 'reliably' on 'hypothesis'
[2022-09-20 20:59:28 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2022-09-20 20:59:28 DEBUG] [__init__:409] Applying before-control 'reliably' on 'activity'
[2022-09-20 20:59:28 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2022-09-20 20:59:28 INFO] [activity:204] Probe: echo-hello
[2022-09-20 20:59:28 DEBUG] [process:52] Running: /usr/bin/echo hello boom
[2022-09-20 20:59:28 DEBUG] [__init__:157] Data encoding detected as 'ascii' with a confidence of 1.0
[2022-09-20 20:59:28 DEBUG] [activity:221]   => succeeded with '{'status': 0, 'stdout': 'hello boom\n', 'stderr': ''}'
[2022-09-20 20:59:28 DEBUG] [__init__:409] Applying after-control 'reliably' on 'activity'
[2022-09-20 20:59:28 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2022-09-20 20:59:28 DEBUG] [hypothesis:221] allowed tolerance is 0
[2022-09-20 20:59:28 INFO] [hypothesis:231] Steady state hypothesis is met!
[2022-09-20 20:59:28 DEBUG] [__init__:409] Applying after-control 'reliably' on 'hypothesis'
[2022-09-20 20:59:28 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2022-09-20 20:59:28 WARNING] [run:641] Rollbacks were explicitly requested to be played
[2022-09-20 20:59:28 INFO] [run:893] Let's rollback...
[2022-09-20 20:59:28 DEBUG] [__init__:409] Applying before-control 'reliably' on 'rollback'
[2022-09-20 20:59:28 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2022-09-20 20:59:28 INFO] [rollback:27] No declared rollbacks, let's move on.
[2022-09-20 20:59:28 DEBUG] [__init__:409] Applying after-control 'reliably' on 'rollback'
[2022-09-20 20:59:28 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2022-09-20 20:59:28 INFO] [run:458] Experiment ended with status: completed
[2022-09-20 20:59:28 DEBUG] [__init__:409] Applying after-control 'reliably' on 'experiment'
[2022-09-20 20:59:28 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py'
[2022-09-20 20:59:28 DEBUG] [__init__:29] Reliably client TLS verification: True
[2022-09-20 20:59:28 DEBUG] [__init__:30] Reliably client scheme: https
[2022-09-20 20:59:28 DEBUG] [experiment:47] Response from https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/aa753650-d64e-4942-841d-f5344612e9bd/executions: 201
[2022-09-20 20:59:28 DEBUG] [__init__:91] Cleaning up controls
[2022-09-20 20:59:28 DEBUG] [__init__:100] Cleaning up control 'reliably'
[2022-09-20 20:59:28 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/src/chaostoolkit-reliably/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2022-09-20 20:59:28 DEBUG] [caching:42] Clearing activities cache
