[2023-02-03 11:27:37 DEBUG] [cli:115] ###############################################################################
[2023-02-03 11:27:37 DEBUG] [cli:116] Running command 'run'
[2023-02-03 11:27:37 DEBUG] [cli:120] Using settings file '/home/runner/.chaostoolkit/settings.yaml'
[2023-02-03 11:27:38 DEBUG] [settings:30] The Chaos Toolkit settings file could not be found at '/home/runner/.chaostoolkit/settings.yaml'.
[2023-02-03 11:27:38 DEBUG] [__init__:449] No controls to apply on 'loader'
[2023-02-03 11:27:38 DEBUG] [loader:129] Fetched experiment: 
    {"tags":[],"title":"Certificate is always valid and has not expired","method":[],"version":"1.0.0","controls":[{"name":"reliably","provider":{"type":"python","module":"chaosreliably.controls.experiment","arguments":{"exp_id":"9430b107-ae8f-4d96-a71f-a44160090eeb","org_id":"8f67bb6a-4944-40af-80b0-921023467cdc"}}}],"description":"Verify the certificate of a remote endpoint for particular aspects: expiration date, alternative subject names, issuer and fingerprint","configuration":{"reliably_host":"reliably.com","reliably_port":"443","reliably_issuer":"","reliably_alt_names":[""],"reliably_fingerprint":"","reliably_expire_after":"7d"},"contributions":{"quality":"none","security":"high","performance":"none","availability":"high"},"steady-state-hypothesis":{"title":"Capture certificate and perform the checks","probes":[{"name":"capture-certificate","type":"probe","provider":{"func":"get_certificate_info","type":"python","module":"chaosreliably.activities.tls.probes","arguments":{"host":"${reliably_host}","port":"${reliably_port}"}},"tolerance":{"name":"verifiy-tls-certificate","type":"probe","provider":{"func":"verify_tls_cert","type":"python","module":"chaosreliably.activities.tls.tolerances","arguments":{"issuer":"${reliably_issuer}","alt_names":"${reliably_alt_names}","expire_after":"${reliably_expire_after}","fingerprint_sha256":"${reliably_fingerprint}"}}}}]}}
[2023-02-03 11:27:38 DEBUG] [__init__:449] No controls to apply on 'loader'
[2023-02-03 11:27:38 DEBUG] [caching:24] Building activity cache...
[2023-02-03 11:27:38 DEBUG] [caching:35] Cached 1 activities
[2023-02-03 11:27:38 INFO] [experiment:58] Validating the experiment's syntax
[2023-02-03 11:27:38 DEBUG] [configuration:63] Loading configuration...
[2023-02-03 11:27:38 DEBUG] [secret:78] Loading secrets...
[2023-02-03 11:27:38 DEBUG] [secret:104] Done loading secrets
[2023-02-03 11:27:38 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2023-02-03 11:27:38 INFO] [experiment:109] Experiment looks valid
[2023-02-03 11:27:38 DEBUG] [caching:42] Clearing activities cache
[2023-02-03 11:27:38 DEBUG] [cli:314] Runtime strategies: hypothesis - default / rollbacks - always
[2023-02-03 11:27:38 DEBUG] [caching:24] Building activity cache...
[2023-02-03 11:27:38 DEBUG] [caching:35] Cached 1 activities
[2023-02-03 11:27:38 DEBUG] [configuration:63] Loading configuration...
[2023-02-03 11:27:38 DEBUG] [secret:78] Loading secrets...
[2023-02-03 11:27:38 DEBUG] [secret:104] Done loading secrets
[2023-02-03 11:27:38 DEBUG] [configuration:160] Loading dynamic configuration...
[2023-02-03 11:27:38 INFO] [run:370] Running experiment: Certificate is always valid and has not expired
[2023-02-03 11:27:38 DEBUG] [__init__:64] Initializing controls
[2023-02-03 11:27:38 DEBUG] [__init__:73] Initializing control 'reliably'
[2023-02-03 11:27:38 DEBUG] [python:196] Control 'configure_control' loaded from '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2023-02-03 11:27:38 DEBUG] [experiment:402] Configure Reliably's experiment control
[2023-02-03 11:27:38 INFO] [experiment:188] Reliably execution: 744e7f35-588a-4f3f-aada-baf0c47e9b62
[2023-02-03 11:27:39 DEBUG] [experiment:74] Starting Reliably state checker now
[2023-02-03 11:27:39 INFO] [run:397] Steady-state strategy: default
[2023-02-03 11:27:39 INFO] [run:401] Rollbacks strategy: always
[2023-02-03 11:27:39 DEBUG] [__init__:459] Applying before-control 'reliably' on 'experiment'
[2023-02-03 11:27:39 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2023-02-03 11:27:39 DEBUG] [run:559] Running steady-state hypothesis before the method
[2023-02-03 11:27:39 INFO] [hypothesis:186] Steady state hypothesis: Capture certificate and perform the checks
[2023-02-03 11:27:39 DEBUG] [__init__:459] Applying before-control 'reliably' on 'hypothesis'
[2023-02-03 11:27:39 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-02-03 11:27:39 DEBUG] [__init__:459] Applying before-control 'reliably' on 'activity'
[2023-02-03 11:27:39 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-02-03 11:27:39 INFO] [activity:215] Probe: capture-certificate
[2023-02-03 11:27:39 DEBUG] [python:33] Activity 'capture-certificate' loaded from '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/activities/tls/probes.py'
[2023-02-03 11:27:39 DEBUG] [activity:235]   => succeeded with '{'conn': {'version': 'TLSv1.3', 'remote_addr': '75.2.60.5:443'}, 'cert': {'fingerprints': {'md5': '0c3464044639adcbc8b94772979f3778', 'sha1': '939f0c65e3e7e3121c1524abfa679facd7806d9f', 'sha256': '0bd6e86c696cfaed1ac97d5f6849a5792c18620c3c8389d0bd98b6fe618e8135'}, 'extensions': {'subjectAltName': ['reliably.com', 'www.reliably.com']}, 'issuer': "CN=R3,O=Let's Encrypt,C=US", 'subject': 'CN=reliably.com', 'serial_int': 262672396126344892037722005403494505859647, 'version': 'v3', 'signature_hash': 'sha256', 'not_valid_before': '2023-01-26T10:10:15', 'not_valid_after': '2023-04-26T10:10:14'}}'
[2023-02-03 11:27:39 DEBUG] [__init__:459] Applying after-control 'reliably' on 'activity'
[2023-02-03 11:27:39 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-02-03 11:27:39 DEBUG] [hypothesis:226] allowed tolerance is {'name': 'verifiy-tls-certificate', 'type': 'probe', 'provider': {'func': 'verify_tls_cert', 'type': 'python', 'module': 'chaosreliably.activities.tls.tolerances', 'arguments': {'issuer': '${reliably_issuer}', 'alt_names': '${reliably_alt_names}', 'expire_after': '${reliably_expire_after}', 'fingerprint_sha256': '${reliably_fingerprint}'}}}
[2023-02-03 11:27:39 DEBUG] [python:33] Activity 'verifiy-tls-certificate' loaded from '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/activities/tls/tolerances.py'
[2023-02-03 11:27:39 DEBUG] [tolerances:29] Cert expires on 2023-04-26T10:10:14
[2023-02-03 11:27:39 DEBUG] [tolerances:53] Alt names: {'reliably.com', 'www.reliably.com'} / Expected alt names: ['']
[2023-02-03 11:27:39 DEBUG] [__init__:459] Applying after-control 'reliably' on 'hypothesis'
[2023-02-03 11:27:39 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-02-03 11:27:39 CRITICAL] [run:571] Steady state probe 'capture-certificate' is not in the given tolerance so failing this experiment
[2023-02-03 11:27:39 WARNING] [run:707] Rollbacks were explicitly requested to be played
[2023-02-03 11:27:39 INFO] [run:944] Let's rollback...
[2023-02-03 11:27:39 DEBUG] [__init__:459] Applying before-control 'reliably' on 'rollback'
[2023-02-03 11:27:39 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2023-02-03 11:27:39 INFO] [rollback:31] No declared rollbacks, let's move on.
[2023-02-03 11:27:39 DEBUG] [__init__:459] Applying after-control 'reliably' on 'rollback'
[2023-02-03 11:27:39 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2023-02-03 11:27:39 INFO] [run:511] Experiment ended with status: failed
[2023-02-03 11:27:39 DEBUG] [__init__:459] Applying after-control 'reliably' on 'experiment'
[2023-02-03 11:27:39 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_experiment_control'
[2023-02-03 11:27:39 DEBUG] [__init__:103] Cleaning up controls
[2023-02-03 11:27:39 DEBUG] [__init__:112] Cleaning up control 'reliably'
[2023-02-03 11:27:39 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2023-02-03 11:27:39 INFO] [experiment:236] Finishing Reliably execution...
[2023-02-03 11:27:40 DEBUG] [experiment:156] Stopping Reliably state checker now
[2023-02-03 11:27:40 INFO] [experiment:289] Finished Reliably execution. Bye!
[2023-02-03 11:27:40 DEBUG] [caching:42] Clearing activities cache
