[2023-04-04T20:36:32.730239+00:00 INFO] [plan:194] ################################################################################
[2023-04-04T20:36:32.730363+00:00 INFO] [plan:195] Starting Reliably experiment: https://app.reliably.dev/api/v1/organization/53c4af8a-6385-4a6a-891d-4286fb3cb8d8/experiments/c71acf34-63ac-46e3-bcc7-d5f2a556a43c/raw
[2023-04-04T20:36:32.730451+00:00 DEBUG] [__init__:206] Loading global control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b'
[2023-04-04T20:36:33.017516+00:00 DEBUG] [caching:24] Building activity cache...
[2023-04-04T20:36:33.017657+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-04-04T20:36:33.017768+00:00 INFO] [experiment:58] Validating the experiment's syntax
[2023-04-04T20:36:33.017820+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-04-04T20:36:33.017863+00:00 DEBUG] [secret:78] Loading secrets...
[2023-04-04T20:36:33.017897+00:00 DEBUG] [secret:103] Done loading secrets
[2023-04-04T20:36:33.024586+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2023-04-04T20:36:33.024678+00:00 INFO] [experiment:109] Experiment looks valid
[2023-04-04T20:36:33.024715+00:00 DEBUG] [caching:42] Clearing activities cache
[2023-04-04T20:36:33.024760+00:00 DEBUG] [caching:24] Building activity cache...
[2023-04-04T20:36:33.024793+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-04-04T20:36:33.024885+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-04-04T20:36:33.024922+00:00 DEBUG] [secret:78] Loading secrets...
[2023-04-04T20:36:33.024951+00:00 DEBUG] [secret:103] Done loading secrets
[2023-04-04T20:36:33.024984+00:00 DEBUG] [configuration:160] Loading dynamic configuration...
[2023-04-04T20:36:33.025069+00:00 INFO] [run:369] Running experiment: Latency remains under 200ms
[2023-04-04T20:36:33.027080+00:00 DEBUG] [__init__:171] Initializing global control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b'
[2023-04-04T20:36:33.027186+00:00 DEBUG] [python:196] Control 'configure_control' loaded from '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/prechecks.py'
[2023-04-04T20:36:33.027325+00:00 DEBUG] [__init__:43] Missing URL for safeguard/precheck call
[2023-04-04T20:36:33.027371+00:00 DEBUG] [__init__:64] Initializing controls
[2023-04-04T20:36:33.027407+00:00 DEBUG] [__init__:73] Initializing control 'reliably'
[2023-04-04T20:36:33.027460+00:00 DEBUG] [python:196] Control 'configure_control' loaded from '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2023-04-04T20:36:33.027539+00:00 DEBUG] [experiment:410] Configure Reliably's experiment control
[2023-04-04T20:36:33.400658+00:00 INFO] [experiment:192] Reliably execution: a472398f-d017-4cfb-b2f9-be40dce55c15
[2023-04-04T20:36:33.716155+00:00 DEBUG] [experiment:552] Sending plan '25a1ade3-ff5c-4a1a-8b7d-74e383baad42' status: running
[2023-04-04T20:36:34.342860+00:00 DEBUG] [experiment:78] Starting Reliably state checker now
[2023-04-04T20:36:34.343030+00:00 INFO] [run:396] Steady-state strategy: after-method-only
[2023-04-04T20:36:34.343576+00:00 INFO] [run:400] Rollbacks strategy: always
[2023-04-04T20:36:34.343665+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'experiment'
[2023-04-04T20:36:34.343769+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2023-04-04T20:36:34.343822+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'experiment'
[2023-04-04T20:36:34.343906+00:00 DEBUG] [python:196] Control 'before_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/prechecks.py'
[2023-04-04T20:36:34.344110+00:00 DEBUG] [__init__:484] Before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' failed
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaoslib/control/__init__.py", line 465, in apply_controls
    apply_python_control(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaoslib/control/python.py", line 179, in apply_python_control
    func(context=context, **arguments)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/prechecks.py", line 29, in before_experiment_control
    run_all(context, configuration, secrets)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/__init__.py", line 193, in run_all
    (handler or proxy).start_all(experiment, configuration, secrets)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/__init__.py", line 142, in start_all
    g.start(experiment, configuration, secrets)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/__init__.py", line 77, in start
    self.probes,
AttributeError: 'ReliablySafeguardGuardian' object has no attribute 'probes'
[2023-04-04T20:36:34.345008+00:00 INFO] [run:663] Playing your experiment's method now...
[2023-04-04T20:36:34.345148+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'method'
[2023-04-04T20:36:34.345252+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2023-04-04T20:36:34.345316+00:00 INFO] [activity:133] No declared activities, let's move on.
[2023-04-04T20:36:34.345398+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'method'
[2023-04-04T20:36:34.345479+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2023-04-04T20:36:34.345563+00:00 DEBUG] [run:590] Running steady-state hypothesis after the method
[2023-04-04T20:36:34.345639+00:00 INFO] [hypothesis:186] Steady state hypothesis: capture-response-time-and-verify-it
[2023-04-04T20:36:34.345711+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'hypothesis'
[2023-04-04T20:36:34.345783+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-04-04T20:36:34.345832+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'hypothesis'
[2023-04-04T20:36:34.345898+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/prechecks.py' does not declare 'before_hypothesis_control'
[2023-04-04T20:36:34.345974+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'activity'
[2023-04-04T20:36:34.346043+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-04-04T20:36:34.346090+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'activity'
[2023-04-04T20:36:34.346153+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/prechecks.py' does not declare 'before_activity_control'
[2023-04-04T20:36:34.346209+00:00 INFO] [activity:215] Probe: measure-endpoint-response-time
[2023-04-04T20:36:34.842331+00:00 DEBUG] [python:33] Activity 'measure-endpoint-response-time' loaded from '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/activities/http/probes.py'
[2023-04-04T20:36:35.080285+00:00 DEBUG] [activity:235]   => succeeded with '0.167046'
[2023-04-04T20:36:35.374187+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'activity'
[2023-04-04T20:36:35.374395+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-04-04T20:36:35.374452+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'activity'
[2023-04-04T20:36:35.374520+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/prechecks.py' does not declare 'after_activity_control'
[2023-04-04T20:36:35.374580+00:00 DEBUG] [hypothesis:226] allowed tolerance is {'name': 'validate-response-time', 'type': 'probe', 'provider': {'func': 'response_time_must_be_under', 'type': 'python', 'module': 'chaosreliably.activities.http.tolerances', 'arguments': {'latency': '${reliably_latency}'}}}
[2023-04-04T20:36:35.374674+00:00 DEBUG] [python:33] Activity 'validate-response-time' loaded from '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/activities/http/tolerances.py'
[2023-04-04T20:36:35.374799+00:00 DEBUG] [tolerances:13] Verify that response time is under: 0.2
[2023-04-04T20:36:35.374851+00:00 INFO] [hypothesis:236] Steady state hypothesis is met!
[2023-04-04T20:36:35.374918+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'hypothesis'
[2023-04-04T20:36:35.374985+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-04-04T20:36:35.375028+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'hypothesis'
[2023-04-04T20:36:35.375088+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/prechecks.py' does not declare 'after_hypothesis_control'
[2023-04-04T20:36:35.375165+00:00 WARNING] [run:706] Rollbacks were explicitly requested to be played
[2023-04-04T20:36:35.375214+00:00 INFO] [run:943] Let's rollback...
[2023-04-04T20:36:35.375283+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'rollback'
[2023-04-04T20:36:35.375349+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2023-04-04T20:36:35.375394+00:00 INFO] [rollback:31] No declared rollbacks, let's move on.
[2023-04-04T20:36:35.375453+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'rollback'
[2023-04-04T20:36:35.375517+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2023-04-04T20:36:35.375572+00:00 INFO] [run:510] Experiment ended with status: completed
[2023-04-04T20:36:35.375620+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'experiment'
[2023-04-04T20:36:35.375680+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_experiment_control'
[2023-04-04T20:36:35.375721+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'experiment'
[2023-04-04T20:36:35.375780+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/prechecks.py' does not declare 'after_experiment_control'
[2023-04-04T20:36:35.375822+00:00 DEBUG] [__init__:103] Cleaning up controls
[2023-04-04T20:36:35.375864+00:00 DEBUG] [__init__:112] Cleaning up control 'reliably'
[2023-04-04T20:36:35.375922+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2023-04-04T20:36:35.375985+00:00 DEBUG] [__init__:265] Cleaning up global control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b'
[2023-04-04T20:36:35.376044+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/prechecks.py' does not declare 'cleanup_control'
[2023-04-04T20:36:35.376097+00:00 INFO] [experiment:245] Finishing Reliably execution...
[2023-04-04T20:36:35.766474+00:00 DEBUG] [experiment:160] Stopping Reliably state checker now
[2023-04-04T20:36:36.063518+00:00 DEBUG] [experiment:552] Sending plan '25a1ade3-ff5c-4a1a-8b7d-74e383baad42' status: completed
[2023-04-04T20:36:36.715861+00:00 INFO] [experiment:298] Finished Reliably execution. Bye!
[2023-04-04T20:36:36.716087+00:00 DEBUG] [caching:42] Clearing activities cache
