[2023-04-04T20:25:32.910291+00:00 INFO] [plan:194] ################################################################################
[2023-04-04T20:25:32.910445+00:00 INFO] [plan:195] Starting Reliably experiment: https://app.reliably.dev/api/v1/organization/53c4af8a-6385-4a6a-891d-4286fb3cb8d8/experiments/c71acf34-63ac-46e3-bcc7-d5f2a556a43c/raw
[2023-04-04T20:25:32.910589+00:00 DEBUG] [__init__:206] Loading global control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b'
[2023-04-04T20:25:33.344255+00:00 DEBUG] [caching:24] Building activity cache...
[2023-04-04T20:25:33.344404+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-04-04T20:25:33.344551+00:00 INFO] [experiment:58] Validating the experiment's syntax
[2023-04-04T20:25:33.344622+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-04-04T20:25:33.344679+00:00 DEBUG] [secret:78] Loading secrets...
[2023-04-04T20:25:33.344726+00:00 DEBUG] [secret:103] Done loading secrets
[2023-04-04T20:25:33.353497+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2023-04-04T20:25:33.353602+00:00 INFO] [experiment:109] Experiment looks valid
[2023-04-04T20:25:33.353824+00:00 DEBUG] [caching:42] Clearing activities cache
[2023-04-04T20:25:33.353916+00:00 DEBUG] [caching:24] Building activity cache...
[2023-04-04T20:25:33.353972+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-04-04T20:25:33.354120+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-04-04T20:25:33.354180+00:00 DEBUG] [secret:78] Loading secrets...
[2023-04-04T20:25:33.354227+00:00 DEBUG] [secret:103] Done loading secrets
[2023-04-04T20:25:33.354280+00:00 DEBUG] [configuration:160] Loading dynamic configuration...
[2023-04-04T20:25:33.354395+00:00 INFO] [run:369] Running experiment: Latency remains under 200ms
[2023-04-04T20:25:33.356742+00:00 DEBUG] [__init__:171] Initializing global control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b'
[2023-04-04T20:25:33.356869+00:00 DEBUG] [python:196] Control 'configure_control' loaded from '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/prechecks.py'
[2023-04-04T20:25:33.357054+00:00 DEBUG] [__init__:43] Missing URL for safeguard/precheck call
[2023-04-04T20:25:33.357126+00:00 DEBUG] [__init__:64] Initializing controls
[2023-04-04T20:25:33.357183+00:00 DEBUG] [__init__:73] Initializing control 'reliably'
[2023-04-04T20:25:33.357265+00:00 DEBUG] [python:196] Control 'configure_control' loaded from '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py'
[2023-04-04T20:25:33.357379+00:00 DEBUG] [experiment:410] Configure Reliably's experiment control
[2023-04-04T20:25:33.814913+00:00 INFO] [experiment:192] Reliably execution: 49513403-242e-4840-8ed2-db85b0844080
[2023-04-04T20:25:34.219874+00:00 DEBUG] [experiment:552] Sending plan '4edac5ea-5a88-4f93-9ceb-8598463148a9' status: running
[2023-04-04T20:25:34.975500+00:00 DEBUG] [experiment:78] Starting Reliably state checker now
[2023-04-04T20:25:34.975701+00:00 INFO] [run:396] Steady-state strategy: after-method-only
[2023-04-04T20:25:34.976435+00:00 INFO] [run:400] Rollbacks strategy: always
[2023-04-04T20:25:34.976554+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'experiment'
[2023-04-04T20:25:34.976697+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2023-04-04T20:25:34.976815+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'experiment'
[2023-04-04T20:25:34.976944+00:00 DEBUG] [python:196] Control 'before_experiment_control' loaded from '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/prechecks.py'
[2023-04-04T20:25:34.977239+00:00 DEBUG] [__init__:484] Before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' failed
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaoslib/control/__init__.py", line 465, in apply_controls
    apply_python_control(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaoslib/control/python.py", line 179, in apply_python_control
    func(context=context, **arguments)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/prechecks.py", line 29, in before_experiment_control
    run_all(context, configuration, secrets)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/__init__.py", line 193, in run_all
    (handler or proxy).start_all(experiment, configuration, secrets)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/__init__.py", line 142, in start_all
    g.start(experiment, configuration, secrets)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/__init__.py", line 77, in start
    self.probes,
AttributeError: 'ReliablySafeguardGuardian' object has no attribute 'probes'
[2023-04-04T20:25:34.978333+00:00 INFO] [run:663] Playing your experiment's method now...
[2023-04-04T20:25:34.978508+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'method'
[2023-04-04T20:25:34.978704+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2023-04-04T20:25:34.978788+00:00 INFO] [activity:133] No declared activities, let's move on.
[2023-04-04T20:25:34.978902+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'method'
[2023-04-04T20:25:34.979000+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2023-04-04T20:25:34.979094+00:00 DEBUG] [run:590] Running steady-state hypothesis after the method
[2023-04-04T20:25:34.979180+00:00 INFO] [hypothesis:186] Steady state hypothesis: capture-response-time-and-verify-it
[2023-04-04T20:25:34.979297+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'hypothesis'
[2023-04-04T20:25:34.979393+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-04-04T20:25:34.979458+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'hypothesis'
[2023-04-04T20:25:34.979544+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/prechecks.py' does not declare 'before_hypothesis_control'
[2023-04-04T20:25:34.979643+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'activity'
[2023-04-04T20:25:34.979737+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-04-04T20:25:34.979802+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'activity'
[2023-04-04T20:25:34.979906+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/prechecks.py' does not declare 'before_activity_control'
[2023-04-04T20:25:34.979983+00:00 INFO] [activity:215] Probe: measure-endpoint-response-time
[2023-04-04T20:25:35.502129+00:00 DEBUG] [python:33] Activity 'measure-endpoint-response-time' loaded from '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/activities/http/probes.py'
[2023-04-04T20:25:35.776633+00:00 DEBUG] [activity:235]   => succeeded with '0.184954'
[2023-04-04T20:25:36.097752+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'activity'
[2023-04-04T20:25:36.098087+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-04-04T20:25:36.100924+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'activity'
[2023-04-04T20:25:36.101140+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/prechecks.py' does not declare 'after_activity_control'
[2023-04-04T20:25:36.101242+00:00 DEBUG] [hypothesis:226] allowed tolerance is {'name': 'validate-response-time', 'type': 'probe', 'provider': {'func': 'response_time_must_be_under', 'type': 'python', 'module': 'chaosreliably.activities.http.tolerances', 'arguments': {'latency': '${reliably_latency}'}}}
[2023-04-04T20:25:36.101391+00:00 DEBUG] [python:33] Activity 'validate-response-time' loaded from '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/activities/http/tolerances.py'
[2023-04-04T20:25:36.101563+00:00 DEBUG] [tolerances:13] Verify that response time is under: 0.2
[2023-04-04T20:25:36.101641+00:00 INFO] [hypothesis:236] Steady state hypothesis is met!
[2023-04-04T20:25:36.101770+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'hypothesis'
[2023-04-04T20:25:36.101886+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-04-04T20:25:36.101998+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'hypothesis'
[2023-04-04T20:25:36.102103+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/prechecks.py' does not declare 'after_hypothesis_control'
[2023-04-04T20:25:36.102213+00:00 WARNING] [run:706] Rollbacks were explicitly requested to be played
[2023-04-04T20:25:36.102296+00:00 INFO] [run:943] Let's rollback...
[2023-04-04T20:25:36.102607+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'rollback'
[2023-04-04T20:25:36.102855+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2023-04-04T20:25:36.102990+00:00 INFO] [rollback:31] No declared rollbacks, let's move on.
[2023-04-04T20:25:36.103117+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'rollback'
[2023-04-04T20:25:36.103212+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2023-04-04T20:25:36.103292+00:00 INFO] [run:510] Experiment ended with status: completed
[2023-04-04T20:25:36.103364+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'experiment'
[2023-04-04T20:25:36.103646+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_experiment_control'
[2023-04-04T20:25:36.103745+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'experiment'
[2023-04-04T20:25:36.103879+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/prechecks.py' does not declare 'after_experiment_control'
[2023-04-04T20:25:36.103944+00:00 DEBUG] [__init__:103] Cleaning up controls
[2023-04-04T20:25:36.104022+00:00 DEBUG] [__init__:112] Cleaning up control 'reliably'
[2023-04-04T20:25:36.104102+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2023-04-04T20:25:36.104178+00:00 DEBUG] [__init__:265] Cleaning up global control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b'
[2023-04-04T20:25:36.104259+00:00 DEBUG] [python:192] Control module '/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/chaosreliably/controls/prechecks.py' does not declare 'cleanup_control'
[2023-04-04T20:25:36.104487+00:00 INFO] [experiment:245] Finishing Reliably execution...
[2023-04-04T20:25:36.557451+00:00 DEBUG] [experiment:160] Stopping Reliably state checker now
[2023-04-04T20:25:36.950056+00:00 DEBUG] [experiment:552] Sending plan '4edac5ea-5a88-4f93-9ceb-8598463148a9' status: completed
[2023-04-04T20:25:37.688291+00:00 INFO] [experiment:298] Finished Reliably execution. Bye!
[2023-04-04T20:25:37.688507+00:00 DEBUG] [caching:42] Clearing activities cache
