[2023-04-05T11:38:52.916471+00:00 INFO] [plan:194] ################################################################################
[2023-04-05T11:38:52.916640+00:00 INFO] [plan:195] Starting Reliably experiment: https://app.reliably.dev/api/v1/organization/53c4af8a-6385-4a6a-891d-4286fb3cb8d8/experiments/c71acf34-63ac-46e3-bcc7-d5f2a556a43c/raw
[2023-04-05T11:38:52.916746+00:00 DEBUG] [__init__:206] Loading global control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b'
[2023-04-05T11:38:53.173215+00:00 DEBUG] [caching:24] Building activity cache...
[2023-04-05T11:38:53.173394+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-04-05T11:38:53.173522+00:00 INFO] [experiment:58] Validating the experiment's syntax
[2023-04-05T11:38:53.173591+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-04-05T11:38:53.173656+00:00 DEBUG] [secret:78] Loading secrets...
[2023-04-05T11:38:53.173713+00:00 DEBUG] [secret:103] Done loading secrets
[2023-04-05T11:38:53.183048+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2023-04-05T11:38:53.183163+00:00 INFO] [experiment:109] Experiment looks valid
[2023-04-05T11:38:53.183213+00:00 DEBUG] [caching:42] Clearing activities cache
[2023-04-05T11:38:53.183382+00:00 DEBUG] [caching:24] Building activity cache...
[2023-04-05T11:38:53.183428+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-04-05T11:38:53.183875+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-04-05T11:38:53.183938+00:00 DEBUG] [secret:78] Loading secrets...
[2023-04-05T11:38:53.184072+00:00 DEBUG] [secret:103] Done loading secrets
[2023-04-05T11:38:53.184294+00:00 DEBUG] [configuration:160] Loading dynamic configuration...
[2023-04-05T11:38:53.184523+00:00 INFO] [run:369] Running experiment: Latency remains under 200ms
[2023-04-05T11:38:53.186783+00:00 DEBUG] [__init__:171] Initializing global control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b'
[2023-04-05T11:38:53.186885+00:00 DEBUG] [python:196] Control 'configure_control' loaded from '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py'
[2023-04-05T11:38:53.187228+00:00 DEBUG] [__init__:43] Missing URL for safeguard/precheck call
[2023-04-05T11:38:53.187297+00:00 DEBUG] [__init__:64] Initializing controls
[2023-04-05T11:38:53.187522+00:00 DEBUG] [__init__:73] Initializing control 'reliably'
[2023-04-05T11:38:53.187666+00:00 DEBUG] [python:196] Control 'configure_control' loaded from '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py'
[2023-04-05T11:38:53.187850+00:00 DEBUG] [experiment:410] Configure Reliably's experiment control
[2023-04-05T11:38:53.491779+00:00 INFO] [experiment:192] Reliably execution: 489173e6-7863-4ca6-a920-625208d26a8a
[2023-04-05T11:38:53.785698+00:00 DEBUG] [experiment:552] Sending plan '6e461f82-3a18-431a-8751-046854d74e0e' status: running
[2023-04-05T11:38:54.411898+00:00 DEBUG] [experiment:78] Starting Reliably state checker now
[2023-04-05T11:38:54.412058+00:00 INFO] [run:396] Steady-state strategy: after-method-only
[2023-04-05T11:38:54.413756+00:00 INFO] [run:400] Rollbacks strategy: always
[2023-04-05T11:38:54.413984+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'experiment'
[2023-04-05T11:38:54.414181+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_experiment_control'
[2023-04-05T11:38:54.414507+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'experiment'
[2023-04-05T11:38:54.414842+00:00 DEBUG] [python:196] Control 'before_experiment_control' loaded from '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py'
[2023-04-05T11:38:54.415440+00:00 DEBUG] [__init__:484] Before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' failed
Traceback (most recent call last):
  File "/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaoslib/control/__init__.py", line 465, in apply_controls
    apply_python_control(
  File "/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaoslib/control/python.py", line 179, in apply_python_control
    func(context=context, **arguments)
  File "/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py", line 29, in before_experiment_control
    run_all(context, configuration, secrets)
  File "/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/__init__.py", line 193, in run_all
    (handler or proxy).start_all(experiment, configuration, secrets)
  File "/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/__init__.py", line 142, in start_all
    g.start(experiment, configuration, secrets)
  File "/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/__init__.py", line 77, in start
    self.probes,
    ^^^^^^^^^^^
AttributeError: 'ReliablySafeguardGuardian' object has no attribute 'probes'
[2023-04-05T11:38:54.416858+00:00 INFO] [run:663] Playing your experiment's method now...
[2023-04-05T11:38:54.417004+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'method'
[2023-04-05T11:38:54.417093+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2023-04-05T11:38:54.417166+00:00 INFO] [activity:133] No declared activities, let's move on.
[2023-04-05T11:38:54.417254+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'method'
[2023-04-05T11:38:54.417329+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2023-04-05T11:38:54.417408+00:00 DEBUG] [run:590] Running steady-state hypothesis after the method
[2023-04-05T11:38:54.417481+00:00 INFO] [hypothesis:186] Steady state hypothesis: capture-response-time-and-verify-it
[2023-04-05T11:38:54.417577+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'hypothesis'
[2023-04-05T11:38:54.417654+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-04-05T11:38:54.417717+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'hypothesis'
[2023-04-05T11:38:54.417785+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py' does not declare 'before_hypothesis_control'
[2023-04-05T11:38:54.417874+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'activity'
[2023-04-05T11:38:54.417943+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-04-05T11:38:54.418004+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'activity'
[2023-04-05T11:38:54.418070+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py' does not declare 'before_activity_control'
[2023-04-05T11:38:54.418141+00:00 INFO] [activity:215] Probe: measure-endpoint-response-time
[2023-04-05T11:38:54.891187+00:00 DEBUG] [python:33] Activity 'measure-endpoint-response-time' loaded from '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/activities/http/probes.py'
[2023-04-05T11:38:55.095616+00:00 DEBUG] [activity:235]   => succeeded with '0.121643'
[2023-04-05T11:38:55.520775+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'activity'
[2023-04-05T11:38:55.521356+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-04-05T11:38:55.521731+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'activity'
[2023-04-05T11:38:55.522082+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py' does not declare 'after_activity_control'
[2023-04-05T11:38:55.522488+00:00 DEBUG] [hypothesis:226] allowed tolerance is {'name': 'validate-response-time', 'type': 'probe', 'provider': {'func': 'response_time_must_be_under', 'type': 'python', 'module': 'chaosreliably.activities.http.tolerances', 'arguments': {'latency': '${reliably_latency}'}}}
[2023-04-05T11:38:55.522956+00:00 DEBUG] [python:33] Activity 'validate-response-time' loaded from '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/activities/http/tolerances.py'
[2023-04-05T11:38:55.523406+00:00 DEBUG] [tolerances:13] Verify that response time is under: 0.2
[2023-04-05T11:38:55.523713+00:00 INFO] [hypothesis:236] Steady state hypothesis is met!
[2023-04-05T11:38:55.524020+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'hypothesis'
[2023-04-05T11:38:55.524312+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-04-05T11:38:55.524673+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'hypothesis'
[2023-04-05T11:38:55.525047+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py' does not declare 'after_hypothesis_control'
[2023-04-05T11:38:55.525425+00:00 WARNING] [run:706] Rollbacks were explicitly requested to be played
[2023-04-05T11:38:55.525714+00:00 INFO] [run:943] Let's rollback...
[2023-04-05T11:38:55.526004+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'rollback'
[2023-04-05T11:38:55.526293+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2023-04-05T11:38:55.526624+00:00 INFO] [rollback:31] No declared rollbacks, let's move on.
[2023-04-05T11:38:55.526923+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'rollback'
[2023-04-05T11:38:55.527206+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2023-04-05T11:38:55.527557+00:00 INFO] [run:510] Experiment ended with status: completed
[2023-04-05T11:38:55.527835+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'experiment'
[2023-04-05T11:38:55.528113+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_experiment_control'
[2023-04-05T11:38:55.528190+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b' on 'experiment'
[2023-04-05T11:38:55.528801+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py' does not declare 'after_experiment_control'
[2023-04-05T11:38:55.528880+00:00 DEBUG] [__init__:103] Cleaning up controls
[2023-04-05T11:38:55.529388+00:00 DEBUG] [__init__:112] Cleaning up control 'reliably'
[2023-04-05T11:38:55.529661+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2023-04-05T11:38:55.530024+00:00 DEBUG] [__init__:265] Cleaning up global control 'reliably-integration-prechecks-4d497aaa6e50b0318434e7e30728f92b'
[2023-04-05T11:38:55.530349+00:00 DEBUG] [python:192] Control module '/home/runner/work/ctkgh/ctkgh/.venv/lib/python3.11/site-packages/chaosreliably/controls/prechecks.py' does not declare 'cleanup_control'
[2023-04-05T11:38:55.530684+00:00 INFO] [experiment:245] Finishing Reliably execution...
[2023-04-05T11:38:55.961463+00:00 DEBUG] [experiment:160] Stopping Reliably state checker now
[2023-04-05T11:38:56.225276+00:00 DEBUG] [experiment:552] Sending plan '6e461f82-3a18-431a-8751-046854d74e0e' status: completed
[2023-04-05T11:38:56.883865+00:00 INFO] [experiment:298] Finished Reliably execution. Bye!
[2023-04-05T11:38:56.884131+00:00 DEBUG] [caching:42] Clearing activities cache
